ministryofjustice/use-of-force

.dockerignore
docker-compose.yml
server/authentication/oauth.js
server/authentication/oauth.test.js

Also updating docker-compose to reference use-of-force rather than formbuilder

Fixing client credentials encoding issue around special characters 

---

.circleci/config.yml
.eslintignore
.gitignore
cypress.json
package-lock.json
package.json
reporter-config.json

Adding integration tests to Circle CI. Also fixing test reporting so summary info can be seen in build reports and publishing jest test reports.

DCS-46 Adding integration tests to circleci

---

integration-tests/pages/tasklistPage.js
server/views/pages/tasklist.html

Just to reduce duplication - based on feedback from previous PR

DCS-54 extracting out macro

---

integration-tests/integration/createIncident/form.spec.js
integration-tests/integration/createIncident/incident-creation.spec.js
integration-tests/pages/checkAnswersPage.js
integration-tests/pages/detailsPage.js
integration-tests/pages/evidencePage.js
integration-tests/pages/newIncidentPage.js
integration-tests/pages/page.js
integration-tests/pages/relocationAndInjuriesPage.js
integration-tests/pages/tasklistPage.js
migrations/20190704000000_form_db.js
server/app.js
server/data/formClient.js
server/data/formClient.test.js
server/routes/checkAnswers.js
server/services/formService.js
server/views/pages/check-answers.html

Probably also need to ensure that all parts are saved as before confirmation as well.
Still need to get confirmation on the error message for when trying to submit an unconfirmed report

DCS-55 Enforce confirmation of a report before submitting

---

README.md
assets/js/add-another.js
cypress.json
integration-tests/db/db.js
integration-tests/integration/createIncident/enter-initial-details.js
integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/incident-creation.spec.js
integration-tests/mockApis/elite2api.js
integration-tests/pages/newIncidentPage.js
integration-tests/plugins/index.js
package-lock.json
package.json
server/app.js
server/config/incident.js
server/data/elite2ClientBuilder.js
server/data/elite2ClientBuilder.test.js
server/data/formClient.js
server/routes/form.js
server/routes/form.test.js
server/services/offenderService.js
server/services/offenderService.test.js
server/views/formPages/incident/newIncident.html

This is still a bit of a WIP.
Still need to:
* Add incident date
* Convert use of force type to a question
* Sanitise incoming data - remove empty items from array, convert ids to numbers
* Workout what we will do regarding search for staff in the MVP
* Look at bundling js

DCS-37  initial details page

---

integration-tests/integration/createIncident/enter-initial-details.js
integration-tests/pages/detailsPage.js
integration-tests/pages/newIncidentPage.js
package.json
server/config/incident.js
server/views/formPages/incident/newIncident.html

Also fixing issue when no witnesses or staff exist.
Also adding start-feature:dev to provide nodemon when writing integration tests

DCS-37 Moving force type to a radio

---

assets/sass/local.sass
integration-tests/mockApis/elite2api.js
integration-tests/pages/tasklistPage.js
integration-tests/plugins/index.js
integration-tests/support/commands.js
package-lock.json
package.json
server/app.js
server/routes/form.js
server/routes/form.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/views/pages/check-answers.html
server/views/pages/incidents.html
server/views/pages/statement/provide.html
server/views/pages/statement/submitted.html
server/views/pages/tasklist.html

This currently hard codes a made up incident: 
<kbd>
</kbd>
Clicking on the "Start now" will go to a page which will allow the user to fill out the statement:
<kbd>
</kbd>
Submitting that report will show the submit page:
<kbd>
</kbd>

DCS-64 Adding initial navigation for filling out statement

---

server/app.js
server/data/formClient.js
server/data/formClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/formService.js
server/services/formService.test.js
server/views/pages/incidents.html

This is still a bit of WIP - still require retrieving names and formatting dates for display in table

DCS-64 Adding retrieval of incidents requiring statements 

---

integration-tests/integration/createIncident/enter-initial-details.spec.js
server/config/incident.js
server/routes/form.js
server/views/formPages/incident/newIncident.html

Additional work will be required to do the frontend work to make this editable (I've split off another ticket). 
<kbd>
</kbd>
Might be better to store this as a separate field, will assess this later

DCS-36 Rendering and storing a default incident date (now). 

---

assets/sass/local.sass
integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/mockApis/elite2api.js
integration-tests/pages/incidentsPage.js
integration-tests/plugins/index.js
server/app.js
server/data/elite2ClientBuilder.js
server/data/elite2ClientBuilder.test.js
server/data/formClient.js
server/data/formClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/offenderService.js
server/services/offenderService.test.js
server/views/pages/incidents.html

Displaying the prisoner name, staff member and date in the incidents which require statements table:
<kbd>
</kbd>

DCS-64 Displaying correct details in todo incident table

---

integration-tests/integration/createIncident/submit-statement.spec.js
integration-tests/pages/newIncidentPage.js
integration-tests/pages/submitStatementPage.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/incidentService.js
server/services/incidentService.test.js
server/utils/utils.js
server/views/formPages/incident/newIncident.html
server/views/pages/statement/provide.html

Adding display of offender details:
<kbd>
</kbd>

DCS-71 Adding display of offender details on statement page

---

server/views/pages/statement/provide.html

The form data is not currently being read
<kbd>
</kbd>

DCS-71 Adding provide statement page.

---

integration-tests/pages/checkAnswersPage.js
server/routes/checkAnswers.js
server/views/pages/check-answers.html

http://localhost:3000/check-answers/-1
The Check Answers page now displays 2 new rows for date and time.
Cypress tests updated

DCS-74: Date and Time of incident displayed

---

server/app.js
server/config/incident.js
server/routes/newIncident.js
server/routes/newIncident.test.js

Also making next path in config a function - in preparation of restructuring urls
At the moment we add the booking id as a suffix to the url - but these will move to be a path
segment within the url.

DCS-38 Renaming form route to newIncident

---

integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/submit-statement.spec.js
integration-tests/integration/createIncident/tasklist.spec.js
server/config/incident.js
server/routes/checkAnswers.js
server/utils/fieldValidation.js
server/utils/nunjucksSetup.js
server/views/formPages/incident/evidence.html
server/views/pages/pagesMacros.njk

http://localhost:3000/form/incident/evidence/-1
The user will now see the validation summary box with the appropriate links if they do not make a response to the questions in the Evidence page.
Have only included summary messages at this point. Will do the code for displaying individual validation messages above each question as a separate ticket as it is a more involved piece of work.

DCS-86: Validation summary messages are displayed in Evidence page

---

integration-tests/pages/submittedPage.js
server/views/pages/submitted.html

Based on feedback from the content designer

DCS-89 Fixing page content

---

server/config/evidenceValidation.test.js
server/config/incident.js
server/utils/fieldValidation.js

Also enforcing yes, no and not known fields to only be allowed values.

DCS-86 Disallow whitespace only on tag and description

---

helm_deploy/use-of-force/templates/job.yaml
job/sendReminders.js

*  Run job every five minutes. 
* Add environmental variables
* prevent concurrent runs 
* Increase history limit of failed and successful jobs
Also holding job running for a minute so I can inspect it whilst its running

DCS-92 Job improvements

---

assets/sass/local.sass
integration-tests/integration/createIncident/submit-statement.spec.js
integration-tests/pages/confirmStatementPage.js
integration-tests/pages/submitStatementPage.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/incidentService.js
server/services/incidentService.test.js
server/views/pages/incidents.html
server/views/pages/statement/confirm.html
server/views/pages/statement/provide.html
server/views/pages/statement/review.html

Adding the ability for staff to view their own statements
Also splitting statement page in to 'provide' and 'confirm' pages

DCS-75 Staff view own statements

---

integration-tests/db/db.js
migrations/20190819000000_form_db.js
server/app.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/index.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/incidentService.js
server/services/incidentService.test.js
server/services/statementService.js
server/services/statementService.test.js

Also renaming db tables:
involved_staff => statements
incidents => reports

DCS-94 Splitting incident and statement service

---

package-lock.json
package.json
server/config.js
server/index.js
server/services/notificationService.js
server/services/notificationService.test.js

This is not currently used by anything

DCS-91 Adding notification service for sending email reminders. 

---

assets/sass/local.sass
integration-tests/integration/createIncident/tasklist.spec.js
server/config/incident.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/newIncident.js
server/services/offenderService.js
server/services/offenderService.test.js
server/views/formPages/incident/newIncident.html
server/views/formPages/incidentMacros.njk
server/views/pages/submitted.html
server/views/pages/tasklist.html

* Fixing date format to show entire month in a few places
* Fixing bug around not retrieving the correct statement for a user
* Changing end of the report summary panel to be a blue pane rather than green (as not end of process)
* Removing bold inner questions
* Improving task list top panel layout to show more of date and offender name on one line without wrapping.

DCS-98 Making additional content changes

---

integration-tests/db/db.js
integration-tests/integration/createIncident/enter-incident-details.spec.js
integration-tests/integration/createIncident/enter-use-of-force-details.spec.js
integration-tests/pages/detailsPage.js
server/views/formPages/incident/details.html
server/views/formPages/incidentMacros.njk

Fixing issue where, if only a single item was selected, it would lead to a single value being passed rather than an array. 
Also improving tests on use-of-force-details page

DCS-98 Fixing issue with single checkbox selection

---

integration-tests/db/db.js
integration-tests/integration/createIncident/enter-incident-details.spec.js
integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/submit-statement.spec.js
integration-tests/pages/newIncidentPage.js
integration-tests/pages/submittedPage.js
integration-tests/plugins/index.js
migrations/20190822000000_form_db.js
server/config/incident.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/newIncident.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/services/reportService.js
server/services/reportService.test.js
server/views/formPages/incident/newIncident.html

Also adding created and updated dates to the statement table

DCS-104 Creating statement records to after confirming report

---

integration-tests/pages/statementSubmittedPage.js
server/routes/incidents.test.js
server/views/pages/statement/confirm.html
server/views/pages/statement/review.html
server/views/pages/statement/submitted.html

Fixing page title and moving to display details horizontally:

DCS-98 Fixing submitted title

---

migrations/20190829093751_form_db.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/services/statementService.js
server/services/statementService.test.js
server/views/pages/statement/your-statement.html

1. New Knex migration to create the statement_amendments table in the DB
2. Updated review.html to display the additional comments plus a new text box for future comments. 
Changed Save buttons
3 Updated unit tests for getStatement()
4.Included new unit test for getAdditionalComments()

DCS-78 a : User can now view additional comments entered previously

---

integration-tests/integration/createIncident/submit-statement.spec.js
server/services/offenderService.js
server/services/offenderService.test.js
server/views/formPages/incident/incidentDetails.html
server/views/pages/check-your-answers.html
server/views/pages/incidents.html
server/views/pages/report-use-of-force.html
server/views/pages/statement/check-your-statement.html
server/views/pages/statement/write-your-statement.html
server/views/pages/statement/your-statement.html

* Removing the leading 0s from day of month
* Changing column headers on incidents page
* Showing offender name, last name first on incidents page
* Removing incident time on incidents page

DCS-108 Fixing date display and content changes to incident page

---

integration-tests/db/db.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/checkYourAnswers.js
server/routes/createReport.js
server/routes/createReport.test.js
server/services/formProcessing.js
server/services/formProcessing.test.js
server/views/pages/report-use-of-force.html

This is unnecessary and simplifies things quite a bit

DCS-109 Removing 'incident' object from stored json payload

---

integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/submit-statement.spec.js
integration-tests/integration/createIncident/tasklist.spec.js
integration-tests/pages/detailsPage.js
integration-tests/pages/tasklistPage.js
server/routes/reportUseOfForce.js
server/services/reportStatusChecker.js
server/services/reportStatusChecker.test.js
server/views/pages/report-use-of-force.html

The link is only available once the whole form is complete. Also now showing in progress status against sections which aren't complete

DCS-100 Making check your answers a conditional link

---

server/config/evidenceValidation.test.js
server/config/incident.js
server/config/incidentDetailsValidation.test.js
server/utils/fieldValidation.js

in nested input and sanitise incoming strings by sanitising them

DCS-111 strip out invalid fields 

---

assets/js/add-another.js
integration-tests/pages/evidencePage.js
integration-tests/pages/relocationAndInjuriesPage.js
server/routes/createReport.js
server/views/formPages/incident/evidence.html
server/views/formPages/incident/incidentDetails.html
server/views/formPages/incident/relocationAndInjuries.html

e.g: 
Previously:
<kbd>
</kbd>
Now: 
<kbd>
</kbd>

DCS-112 inlining remove buttons for add-another components

---

.circleci/config.yml
server/config.js
server/data/dataAccess/db.js
server/data/incidentClient.js
server/index.js
server/services/involvedStaffService.js
server/services/notificationService.js
server/services/notificationService.test.js
server/services/reportService.js
server/services/reportService.test.js

This will inform them that they need to complete their statements

DCS-90 sending initial notification to staff. 

---

integration-tests/db/db.js
package.json
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/checkYourAnswers.js
server/routes/createReport.js
server/routes/incidents.js
server/routes/reportUseOfForce.js
server/services/notificationService.js
server/services/reportService.js
server/services/reportService.test.js

Also fixing issue where the UoF reporter was incorrectly being sent an email meant for involved staff

DCS-90 moving to return field names which match js conventions.

---

job/sendReminders.js
server/data/incidentClient.js
server/data/incidentClient.test.js

Needed to set up thread local for storing and retrieving db client
Also was missing await and fixed query

DCS-93 fix job and returning required fields for job

---

migrations/20190906000000_form_db.js

Also adding index for polling from queue

DCS-110 Coping with optional staff id

---

job/reminders/reminderSender.js
server/services/notificationService.js
server/services/notificationService.test.js
server/services/reportService.js
server/services/reportService.test.js

Calculate deadline for submitting statements from submitted date rather than incident date

DCS-93 Fix deadline date and time

---

integration-tests/db/db.js
integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/pages/yourReportPage.js
job/reminders/reminderSender.test.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/views/pages/report-use-of-force.html
server/views/pages/your-report.html
server/views/pages/your-reports.html

Adding offender name and number and report name and submitted date.
Changing title to 'Use of force report'
Also fixing names of fields on the tasklist page and buttons on the incidents page.

 DCS-76 Adding additional info to view-report page

---

integration-tests/integration/createIncident/view-all-incidents.spec.js
integration-tests/integration/createIncident/view-your-reports.spec.js
integration-tests/mockApis/auth.js
integration-tests/pages/allIncidentsPage.js
integration-tests/pages/incidentsPage.js
integration-tests/plugins/index.js
server/config/types.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/middleware/authorisationMiddleware.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.js
server/routes/testutils/appSetup.js
server/services/reportService.js
server/services/reportService.test.js
server/views/pages/all-incidents.html
server/views/partials/incidentPage.html

This will be the default tab that the reviewer can see and will not be
available to other users.
At the moment this returns all reports:
* incomplete refers to submitted reports with outstanding statements
* complete refers to submitted reports with all statements complete.
Still need to filter reports by the users active caseload
Also need to mark reports as being complete once all statements are submitted.

DCS-129 Adding all incidents page

---

assets/sass/local.sass
integration-tests/db/db.js
integration-tests/integration/createIncident/view-all-incidents.spec.js
integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/pages/allIncidentsPage.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/reportService.js
server/services/reportService.test.js
server/views/pages/all-incidents.html

Adding overdue label to incidents which have overdue statements.

DCS-129 Adding overdue label to reports on all incidents

---

integration-tests/db/db.js
integration-tests/integration/reviewer/view-statement.spec.js
integration-tests/pages/viewStatementsPage.js
server/app.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/index.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.js
server/services/reviewService.js
server/services/reviewService.test.js
server/views/pages/all-incidents.html
server/views/pages/check-your-answers.html
server/views/pages/reviewer/view-statement.html
server/views/pages/reviewer/view-statements.html

Adding view statements page for reviewers.

DCS-130 Adding view statements page

---

integration-tests/db/db.js
integration-tests/integration/reviewer/view-statement.spec.js
integration-tests/integration/reviewer/view-statements.spec.js
integration-tests/pages/reviewStatementPage.js
integration-tests/pages/viewStatementsPage.js
integration-tests/plugins/index.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/routes/incidents.js
server/routes/index.js
server/routes/statements.test.js
server/services/reviewService.js
server/services/reviewService.test.js
server/views/pages/reviewer/view-statement.html
server/views/pages/reviewer/view-statements.html
server/views/pages/statement/add-comment-to-statement.html
server/views/pages/statement/check-your-statement.html
server/views/pages/statement/your-statement.html
server/views/pages/statementDetailMacro.njk

Extracting out macro for view statements section

DCS-130 Adding view statement page. 

---

server/index.js
server/routes/incidents.js
server/routes/incidents.test.js
server/services/reportService.js
server/services/reportService.test.js
server/services/reviewService.js
server/services/reviewService.test.js

Moving missing resource check down to service layer

DCS-65 moving review methods to review service. 

---

assets/sass/local.sass
integration-tests/integration/reportPages/enter-incident-details.spec.js
integration-tests/pages/newIncidentPage.js
server/config/incident.js
server/config/incidentDetailsValidation.test.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/createReport.js
server/routes/createReport.test.js
server/services/reportService.js
server/services/reportService.test.js
server/utils/dateSanitiser.js
server/utils/dateSanitiser.test.js
server/utils/fieldValidation.js
server/utils/nunjucksSetup.js
server/views/formPages/incident/incidentDetails.html

First stab at capturing incident date.
This currently:
* First, performs some more complicated checks in the sanitiser and adds the results as flags to the model
* Secondly, asserts the presence or absence of these flags in the validator
This is because it was a bit fiddly to model adding a clause to one property only when a subset of other properties are valid. 
Still Todo:  
* Haven't been able to add all the validation rules 
* Only possible to display a single error message on a date component so only showing the first - we could possible combine them and show a list. 
* The more complicated rules: date in future, time in future, invalid date aren't linked to any field - might be worth looking at implementing a custom validator for them.

DCS-65 Capturing incident date

---

job/reminders/reminderPoller.js
job/reminders/reminderPoller.test.js
job/sendReminders.js
server/index.js
server/utils/azure-appinsights.js

Also increasing number of reminders to process to a maximum of 50 every 5 minutes (up from 1)

DCS-144 Adding application insights to reminder job

---

assets/sass/local.sass
integration-tests/integration/statements/submit-statement.spec.js
integration-tests/pages/submitStatementPage.js
migrations/20190923000000_form_db.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/routes/statements.js
server/views/pages/report-use-of-force.html
server/views/pages/your-reports.html
server/views/pages/your-statements.html

Showing 'start statement' or 'continue statement' depending on whether revisiting an edited statement or not
Also fixing display of buttons and labels - so consistent with other buttons and labels within the same page.

DCS-127 Fixing statement buttons

---

server/config/incident.js
server/config/incidentDetailsValidation.test.js
server/utils/dateSanitiser.js
server/utils/dateSanitiser.test.js
server/views/formPages/incident/incidentDetails.html

including:
* Showing new error messages
* Fix issue around being unable to parse 0 minutes or 0 hours
* Removing unnecessary `.`

DCS-65 Fix issues around recording dates

---

integration-tests/db/db.js
integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/mark-reports-as-complete.spec.js
integration-tests/integration/createIncident/tasklist.spec.js
integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/integration/createIncident/view-your-reports.spec.js
integration-tests/integration/reportPages/check-your-answers.spec.js
integration-tests/integration/reportPages/enter-incident-details.spec.js
integration-tests/integration/reviewer/view-all-incidents.spec.js
integration-tests/integration/reviewer/view-report.spec.js
integration-tests/integration/reviewer/view-statement.spec.js
integration-tests/integration/reviewer/view-statements.spec.js
integration-tests/integration/statements/save-additional-comment.spec.js
integration-tests/integration/statements/submit-statement.spec.js
integration-tests/mockApis/auth.js
package-lock.json
server/config/incident.js
server/config/relocationAndInjuriesValidation.test.js
server/data/authClientBuilder.js
server/data/authClientBuilder.test.js
server/services/formProcessing.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/services/userService.js
server/utils/fieldValidation.js
server/utils/fieldValidation.test.js

Now handles a single empty space.

DCS-116 Currently missing username and name validation (UoF)

---

job/reminders/reminderPoller.js
job/reminders/reminderPoller.test.js
job/reminders/reminderSender.js
job/reminders/reminderSender.test.js
job/sendReminders.js
package.json
server/data/incidentClient.js
server/data/incidentClient.test.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/index.js
server/services/eventPublisher.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/services/notificationService.js
server/services/notificationService.test.js
server/services/reportService.js
server/services/reportService.test.js

* Raising events on each success/failure of sending emails
* Raising events on each start and stop of the batch job
For each email, we attach report and statement ids as properties, this required a bit of a rework around how we save statements.

DCS-134 publishing application events

---

job/reminders/reminderPoller.js
server/services/eventPublisher.js
server/services/notificationService.js
server/services/notificationService.test.js
server/views/pages/reviewer/view-statements.html

also removing a bit of unused html from the statement view

DCS-157 PR feedback, moving logging into publisher

---

server/app.js

Error handlers require magical fourth parameter otherwise they don't actually register!

DCS-157 Fixing error logging

---

job/reminders/reminderSender.js
job/reminders/reminderSender.test.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/services/notificationService.js
server/services/notificationService.test.js
server/services/reportService.js
server/services/reportService.test.js

DCS-179 Adding submitted date to available variables

---

server/data/reportingClient.js
server/data/reportingClient.test.js
server/index.js
server/routes/api.js
server/routes/api.test.js
server/services/reportingService.js
server/services/reportingService.test.js

DCS-192 Adding most frequently involved prisoner list
Also removing the user_id column from staff report as per the DCS-190 story

DCS-192 Adding most frequently involved prisoner list

---

migrations/20200131000000_form_db.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/data/reportingClient.js
server/data/reportingClient.test.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/services/reportService.js
server/services/reportService.test.js

Added a new `deleted` columns and views for each table. 
Updated unique report index per booking/user to ignore reports which are deleted. 
Also using views when selecting or updating single table and using original tables when joining.

DCS-336 Initial work to allow soft delete of reports

---

integration-tests/integration/reviewer/view-report.spec.js
integration-tests/pages/reviewer/allIncidentsPage.js
integration-tests/pages/reviewer/viewReportPage.js
integration-tests/pages/reviewer/viewStatementsPage.js
integration-tests/pages/yourReports/yourReportPage.js
server/routes/coordinator.js
server/routes/coordinator.test.js
server/routes/incidents.test.js
server/routes/index.js
server/views/pages/all-incidents.html
server/views/pages/coordinator/confirm-deletion.html
server/views/pages/reportDetailMacro.njk
server/views/pages/reviewer/view-report.html
server/views/pages/reviewer/view-statements.html

* Removed the view statements link from 'all-incidents' 
* Added a new column to display the delete button if coordinator. 
* Removed the delete button from view-report
* Added details about the report to the confirm deletion page
* Added radio buttons to allow confirm/decline

DCS-336 Design changes based on feedback from content designer

---

job/reminders/reminderPoller.js
job/reminders/reminderPoller.test.js
job/reminders/reminderSender.js
job/sendReminders.js

Always set next reminder date if reminder exists. Also adding more logging

DCS-374 Fixing reminder polling

---

integration-tests/integration/reportPages/enter-use-of-force-details.spec.js
integration-tests/integration/seedData.js
integration-tests/pages/createReport/checkAnswersPage.js
integration-tests/pages/createReport/useOfForceDetailsPage.js
integration-tests/pages/sections/reportDetails.js
server/config/forms/useOfForceDetailsForm.js
server/config/forms/useOfForceDetailsValidation.test.js
server/routes/checkYourAnswers.test.js
server/routes/model/reportSummary.js
server/services/reportStatusChecker.test.js
server/views/formPages/incident/useOfForceDetails.html
server/views/pages/reportDetailMacro.njk

http://localhost:3000/report/-1/use-of-force-details
Yes / No radio button group added allowing user to record whether and pain inducing techniques were used.

DCS 237 pain inducing techniques

---

package-lock.json
package.json

new [bug](https://github.com/cypress-io/cypress/issues/6788) in cypress which fails docker build.
Temporarily reverting cypress whilst its fixed.. have work on a separate branch to ensure we don't install cypress during the docker build

DCS-330 Fixing cypress error

---

server/data/reportingClient.js
server/data/reportingClient.test.js
server/services/reportingService.js
server/services/reportingService.test.js

Moving to use incident date rather than submitted date in overview report.
Also now showing another row which shows summary information about in progress reports

DCS-417 overview report fixes

---

server/data/elite2ClientBuilder.js
server/data/elite2ClientBuilder.test.js
server/data/reportingClient.js
server/data/reportingClient.test.js
server/index.js
server/routes/api.js
server/routes/api.test.js
server/services/heatmapBuilder.js
server/services/heatmapBuilder.test.js
server/services/offenderService.js
server/services/reportingService.js
server/services/reportingService.test.js

This shows locations by number of incidents at a specific hour
This is to allow coordinators to be able to determine which parts of a prison
have the most incidents of usages of force.
This should allow the production of something like this:
<kbd>
</kbd>
This will produce a CSV where location rows are sorted to show the most number
of incidents first and then using order of location name to resolve ties.

DCS-208 Adding heat map report

---

server/data/reportingClient.js
server/data/reportingClient.test.js

The "enum" types need to be unwrapped

DCS-417 fix issue where enums were being directly passed to postgres

---

.circleci/config.yml
.dockerignore
.eslintignore
.gitignore
Dockerfile
package-lock.json
package.json
server/app.js
tsconfig.json

Moving to deploy typescript compiled application as part of the
docker image.
Also updating dev scripts to run against compiled location.
When debugging, breakpoints will have to be set in the compiled code
rather than the typescript/js source - all resources will be copied across
automatically in :dev mode
The docker multistage build reduces image size from 850MB to just under 300MB

DCS-429 Moving to deploy compiled application

---

server/services/religiousGrouping/religiousGrouping.js
server/services/religiousGrouping/religiousGrouping.test.js
server/services/reportingService.test.js

Use new religionCode values from elite2-api /api/prisoners response instead of religion.

DCS-198 Incidents by religion

---

.eslintrc.json
server/utils/azure-appinsights.ts

Fix broken app insights configuration

DCS-199 Incidents by ethnicity

---

assets/sass/local.sass
integration-tests/integration/coordinator/add-involved-staff.spec.js
integration-tests/integration/coordinator/remove-involved-staff.spec.js
integration-tests/integration/createIncident/mark-reports-as-complete.spec.js
integration-tests/integration/createIncident/view-your-reports.spec.js
integration-tests/integration/reviewer/view-all-incidents.spec.js
integration-tests/integration/reviewer/view-report.spec.js
integration-tests/integration/statements/save-additional-comment.spec.js
integration-tests/integration/statements/submit-statement.spec.js
integration-tests/pages/reviewer/allIncidentsPage.js
integration-tests/pages/yourReports/yourReportsPage.js
integration-tests/pages/yourStatements/yourStatementsPage.js
server/routes/incidents.js
server/routes/statements.js
server/views/pages/all-incidents.html
server/views/pages/your-reports.html
server/views/pages/your-statements.html

Also:
* Adding messages for when no rows appear in report/statement tables
* Removing report headers
* Changing buttons to links where not actions

DCS-405 Adding prison number column

---

server/data/incidentClient.js
server/data/incidentClient.test.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/routes/incidents.js
server/routes/statements.js
server/services/reportService.js
server/services/reportService.test.js
server/services/statementService.js
server/services/statementService.test.js

Ensuring complete reports/statements are ordered by descending incident date

DCS-473 Fixing sort order 

---

server/views/tagManager/bodyContent.html
server/views/tagManager/headContent.html

Don't escape googleTagManagerEnvironment string.

DCS-483 Tag 'submit a report'. 

---

server/data/authClientBuilder.test.ts
server/data/authClientBuilder.ts
server/data/elite2ClientBuilder.test.ts
server/data/elite2ClientBuilder.ts
server/data/restClient.ts
server/index.js
server/utils/errorSanitiser.test.ts
server/utils/errorSanitiser.ts

Based on PAT-869 https://github.com/ministryofjustice/pathfinder/pull/471/files

DCS-491 stop confidential information appearing in logs

---

server/routes/changePrison.js
server/routes/changePrison.test.js
server/routes/checkYourAnswers.js
server/routes/checkYourAnswers.test.js
server/routes/createReport.js
server/routes/createReport.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.ts
server/services/locationService.test.ts
server/services/locationService.ts
server/services/offenderService.test.ts
server/services/offenderService.ts
server/services/reportService.js
server/services/reportService.test.js
server/services/reportingService.test.ts
server/types/uof.d.ts

getLocation() and getIncidentLocations() moved from  offenderService to LocationService

DCS-495: code refactor:

---

server/services/locationService.ts

DCS-495: remove unnecessary comment

---

Dockerfile
assets/sass/local.sass
server/app.js
server/routes/incidents.js
server/routes/reportUseOfForce.js
server/routes/statements.js
server/utils/nunjucksSetup.js
server/views/partials/header.html

Also:
* Moving links into nunjucks global
* Changing service name in banner
* Moving to env variable to exclude cypress
* Also moving to the same session management options as prison staff hub

DCS-398 Splitting header into 2 different links

---

integration-tests/integration/coordinator/add-involved-staff.spec.js
integration-tests/integration/coordinator/remove-involved-staff.spec.js
integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/integration/reviewer/view-report.spec.js
integration-tests/pages/reviewer/viewReportPage.js
integration-tests/pages/yourReports/yourReportPage.js
server/views/pages/check-your-answers.html
server/views/pages/reviewer/view-report.html
server/views/pages/your-report.html

Check your answers:
<kbd>
</kbd>
Your report
<kbd>
</kbd>

DCS-451 Replacing buttons with link

---

assets/sass/local.sass
server/views/pages/report-use-of-force.html

styling changes to 
1. reverse the bold from details to labels for name, prison and date of birth 
2. apply different widths to image, name, prison and date of birth 
3. make content 3/4th wide

DCS-447 styling and spacing changes

---

server/views/formPages/incident/evidence.html

page looks like this
<bkr>
</bkr>

added 20px margin-top to label

---

assets/sass/local.sass
integration-tests/integration/statements/submit-statement.spec.js
integration-tests/integration/statements/view-your-statements.spec.js
integration-tests/mockApis/data.js
integration-tests/pages/yourStatements/yourStatementsPage.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/routes/statements.js
server/views/pages/your-statements.html

DCS-569 Highlighting overdue statements on 'Your statements'

---

server/views/pages/your-statements.html

<kbd><img width="1064" alt="Screenshot 2020-07-22 at 11 50 12" src="https://user-images.githubusercontent.com/1517745/88167949-879dd680-cc11-11ea-9968-76e162663e72.png">
</kbd>

DCS-570 Making continue button secondary and adding visually hidden text

---

integration-tests/db/db.js
integration-tests/integration/statements/view-your-statements.spec.js
integration-tests/pages/sections/pagination.js
integration-tests/pages/yourStatements/yourStatementsPage.js
integration-tests/plugins/index.js
server/app.js
server/data/dataAccess/db.ts
server/data/statementsClient.test.ts
server/data/statementsClient.ts
server/routes/statements.test.ts
server/routes/statements.ts
server/services/statementService.test.ts
server/services/statementService.ts
server/utils/nunjucksSetup.ts
server/utils/page.test.ts
server/utils/page.ts
server/views/pages/your-statements.html
server/views/partials/incidentSearchPanel.html

Adding pagination to statements. Pagination only appears if more results than the page size (20)
<kbd><img width="976" alt="Screenshot 2020-07-24 at 09 55 33" src="https://user-images.githubusercontent.com/1517745/88375655-dd9a8780-cd93-11ea-8c7c-dcf4e67e5293.png"></kbd>

DCS-570 Adding pagination to statements

---

assets/sass/local.sass
server/views/pages/reportDetailMacro.njk
server/views/pages/reportDetailSectionsMacros.njk
server/views/pages/reviewer/view-report.html
server/views/pages/statementDetailMacro.njk
server/views/pages/your-report.html

This ticket was to provide a print option for the report pages.
screenshots below
1. report page prior to changes (from T3)
2. report page after change
3. print dialogue box after change
--------------
------------

Dcs 629 user can print their report

---

integration-tests/integration/reportPages/change-prison.spec.js
integration-tests/integration/reportPages/check-your-answers.spec.js
package.json
server/config/incident.js
server/routes/createReport.test.ts
server/routes/createReport.ts
server/routes/incidentDetails.test.ts
server/routes/incidentDetails.ts
server/routes/index.ts
server/services/report/reportStatusChecker.js
server/services/report/reportStatusChecker.test.js
server/views/formPages/formTemplate.html
server/views/pages/reportDetailMacro.njk

Always assume edit mode once the report is complete rather than tracking where the user navigated from

DCS-640 Simplifying routing logic 

---

assets/js/main.js
integration-tests/integration/createIncident/adding-involved-staff.spec.js
integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/reportPages/change-prison.spec.js
integration-tests/integration/reportPages/check-your-answers.spec.js
integration-tests/integration/reportPages/enter-use-of-force-details.spec.js
integration-tests/pages/createReport/checkAnswersPage.js
integration-tests/pages/createReport/evidencePage.js
integration-tests/pages/createReport/incidentDetailsPage.js
integration-tests/pages/createReport/relocationAndInjuriesPage.js
integration-tests/pages/createReport/staffInvolvedPage.js
integration-tests/pages/createReport/useOfForceDetailsPage.js
server/config/incident.js
server/routes/addInvolvedStaff.test.ts
server/routes/addInvolvedStaff.ts
server/routes/createReport.ts
server/views/formPages/addingStaff/staff-involved.html
server/views/formPages/formTemplate.html
server/views/pages/reviewer/view-statements.html
server/views/pages/statement/your-statement.html
server/views/pages/your-report.html

Also extracting inline javascript for print links out

DCS-630 fix navigation around editing involved staff

---

assets/sass/local.sass
server/views/pages/reviewer/view-statements.html

respecting whitespace, correcting label and fixing date display

DCS-630 fixing print display of content

---

integration-tests/pages/createReport/staffMemberNotFoundPage.js
server/routes/addInvolvedStaff.test.ts
server/routes/addInvolvedStaff.ts
server/views/formPages/addingStaff/staff-member-name.html
server/views/formPages/addingStaff/staff-member-not-found.html
server/views/formPages/formTemplate.html

Fixing problems found in peer test.

DCS-647 Add staff through user search and support multiple matches.

---

server/views/formPages/addingStaff/staff-involved.html

and removed capital A from email address

DCS-720: fixed alignment of page title

---

assets/sass/local.sass
server/views/formPages/addingStaff/staff-involved.html

Also did tidy up of html missed in another ticket

DCS-722 prevent content shift following 'add another'

---

server/views/pages/coordinator/confirm-statement-deletion.html

screenshot
**before**
**after**

DCS-723 - reduced space between page title, body text and button by half

---

server/views/pages/statement/check-your-statement.html

changed test to 'Accept and send'
**before**
**after**

DCS-726 button text changed

---

integration-tests/integration/login.spec.js
integration-tests/mockApis/auth.js
integration-tests/mockApis/elite2api.js
integration-tests/pages/yourStatements/yourStatementsPage.js
integration-tests/plugins/index.js

Test needed to verify the application logs current user out if a new user logs in.

DCS-812: login integration test added. 

---

integration-tests/pages/sections/reportDetails.js
server/views/pages/reportDetailMacro.njk

:bug: Make sure the authorising manager is displayed in read-only views.

DCS-848 Add question to record which manager authorised the use of force. 

---

integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/integration/reportPages/enter-incident-details.spec.js
integration-tests/pages/sections/reportDetails.js
integration-tests/pages/yourReports/yourReportPage.js
server/views/pages/reportDetailMacro.njk

:bug: Fixed typo and added another test.

DCS-848 Add question to record which manager authorised the use of force.

---

integration-tests/pages/sections/reportDetails.js
server/config/types.js

pages now appear like this
**use-of-force-details**
**check-your-answers**
**view-report**
**print**

DCS-853 changed label for restraint position

---

integration-tests/integration/reportPages/check-your-answers.spec.js
integration-tests/integration/reportPages/relocation-and-injuries.spec.js
integration-tests/pages/createReport/relocationAndInjuriesPage.js
server/config/forms/relocationAndInjuriesForm.js
server/config/forms/relocationAndInjuriesValidation.test.js
server/config/types.ts
server/services/reportSummary.ts
server/utils/nunjucksSetup.ts
server/views/formPages/incident/relocationAndInjuries.html
server/views/formPages/incidentMacros.njk

Relocation and injuries page now includes additional options for Was the prisoner compliant question. 
When selecting 'other', the user is provided with a free form text box.

DCS 850 change to relocation question

---

server/views/formPages/incident/relocationAndInjuries.html
server/views/formPages/incidentMacros.njk

Fixed preselect bug and renamed macro sections to be more relevant to the relocation compliancy and relocation type questions.

DCS-914 fixed relocation compliancy preselect bug

---

server/config/types.ts
server/data/statementsClient.test.ts
server/data/statementsClient.ts
server/data/statementsClientTypes.ts
server/routes/maintainingReports/reviewer.test.ts
server/routes/maintainingReports/reviewer.ts
server/services/drafts/draftReportService.test.ts
server/services/reviewService.test.ts
server/services/reviewService.ts
server/services/statementService.ts
server/services/statementServiceTypes.ts

and tidying up retrieval of reviewer statements

DCS-872 supporting DISPUTED statements 

---

assets/sass/local.sass
integration-tests/integration/coordinator/add-involved-staff.spec.js
integration-tests/integration/coordinator/remove-involved-staff.spec.js
integration-tests/integration/reviewer/view-statement.spec.js
integration-tests/integration/reviewer/view-statements.spec.js
integration-tests/pages/reviewer/viewStatementsPage.js
migrations/20210401000000_form_db.js
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/data/incidentClientTypes.ts
server/data/statementsClientTypes.ts
server/routes/maintainingReports/reviewer.test.ts
server/services/reviewService.test.ts
server/services/reviewService.ts
server/views/macros.njk
server/views/pages/not-completed-incidents.html
server/views/pages/reviewer/view-statements.html

Can not deploy yet as need to set up the View removal request page
Pages without and then with a removal request

DCS 908 UoF display removal request flag and link on incident page

---

server/views/partials/breadcrumbs.njk

This currently goes to a page that most users can't access

DCS-1065 Fix breadcrumb

---

integration-tests/integration/reviewer/view-completed-incidents.spec.js
server/routes/maintainingReports/reviewer.test.ts
server/routes/maintainingReports/reviewer.ts
server/views/partials/incidentSearchPanel.html

Format for date period changed from d mm yyyy to DD/MM/YYYY

DCS-1132: Search date format changed in completed incidents page

---

helm_deploy/use-of-force/templates/ingress.yaml

``` 
helm template release ./helm_deploy/use-of-force --dependency-update   --values ./helm_deploy/values-dev.yaml 
```

DCS-1310 Including annotations

---

.circleci/config.yml
Dockerfile
README.md
job/reminders/reminderPoller.test.ts
package.json
server/data/healthcheck.test.js
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/data/incidentClientTypes.ts

Updated Node because of issues highlighted in security report

DCS-1341 upgrade to Node 16

---

.circleci/config.yml

and make circle config more aligned with template project

Update security channel 

---

server/app.ts

This was preventing jquery from being loaded from the CDN

DCS-1434 Fix cross origin embedded policy after helmet upgrade

---

helm_deploy/use-of-force/Chart.yaml
helm_deploy/use-of-force/values.yaml
helm_deploy/values-prod.yaml

Prod alerts to go to new elp_alerts slack channel. 
Dev and Pre-prod to digital-prison-service-dev (as is in BVL project)

DCS-1081 update Promethues alerts

---

database_refresh/03-prometheus-alert.yaml

This isn't automated so I've manually applied the change and updating here for future reference

DCS-1672 Update alert channel for refresh job

---

helm_deploy/use-of-force/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

This reverts commit acf74d18a2f155e059a78c02adc8c3b089ade974.

Revert "DCS-1647: ✨ Disable data extractor in prod (#594)"

---

server/views/partials/incidentPage.html

DCS-2141 Add Temporary notification banner

---

helm_deploy/use-of-force/templates/_envs.tpl

Forgot to do this in previous PR (which has now been merged in)

MAP-114 update helm template

---

helm_deploy/use-of-force/Chart.yaml
helm_deploy/values-dev.yaml

- Use the development version of the extractor
- Change the executed args of the extractor job to try to upload to the data platform

Changed config for extractor to AP job

---

helm_deploy/values-dev.yaml

Upversioned extractor image to add openssl and jq

---

integration-tests/integration/reportPages/relocation-and-injuries.cy.js
server/config/types.ts

**relocation and injuries page**
check-your-answers
your-report

MAP-578 add 'restraint' and 'kneeling' options to prisoner compliance Q

---

package-lock.json
package.json

to fix 
follow-redirects and Ip that affect Notify and Sass respectively

MAP-830 update dependencies

---

package-lock.json
package.json

[MAP-1573](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1573)
[MAP-1573]: https://dsdmoj.atlassian.net/browse/MAP-1573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1573 updated sub dependency to overcome CVE

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

missed the -dev for dev env and //https for preprod

MAP-1548 correct mistakes in helm config

---

integration-tests/mockApis/nomisMappingApi.js
server/data/nomisMappingClient.ts
tsconfig.json

used the incorrect endpoint before

MAP-1931 call nomis mapping on a different endpoint

---

.circleci/config.yml
Dockerfile
job/sendReminders.ts
package-lock.json
package.json
server/app.ts
server/data/index.ts
server/data/prisonClient.ts
server/data/redisClient.ts
server/services/reportSummary.ts

Redis didn't store the auth token and it created a bug.

MAP-1943 Revert redis connect

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

https://dsdmoj.atlassian.net/browse/MAP-2034

Add scheduled downtime to non-prod environments

---

Dockerfile
server/config.js

align with [template project ](https://github.com/ministryofjustice/hmpps-template-typescript/blob/main/Dockerfile)
The only additional things are installing python and the saving pf pem file (these were in the dockerfile already)

MAP-2229 align dockerfile with template project

---

feature.env
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.js
server/utils/nunjucksSetup.ts

enabling edit features to be displayed in dev only

MAP-2319 add feature flag 

---

migrations/20250519000000_form_db.js

Also rename columns and add index on report_id

MAP-2319 db migration to better differentiate report owner edits.

---

assets/js/moj-frontend-init.js
package-lock.json
package.json
server/views/partials/layout.html
tsconfig.json

- Updates the moj frontend dependency version
- Import and initialise the dependency
- Link to MOJ frontend stylesheet

Add MOJ frontend

---

.circleci/config.yml

[MAP-2525](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?issueParent=391911%2C286167&selectedIssue=MAP-2525)
[MAP-2525]: https://dsdmoj.atlassian.net/browse/MAP-2525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-2525 circle orb updated

---

server/views/formPages/incident/partials/taser.njk

change to question wording as per UCD

MAP-2436 change wording of taser questions

---

server/views/partials/miniProfile/template.njk

**Related to ticket:** [MAP-2587](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=625e8c18fd06270069bf7ddd&selectedIssue=MAP-2587)
**Changes made:**
- Removed unnecasry space
- Replaced 'Offender name' with 'Prisoner name' as per the designs
[MAP-2587]: https://dsdmoj.atlassian.net/browse/MAP-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-2587 - update detail fields to match design

---

server/routes/maintainingReports/coordinator.ts

clearing out flash before reusing because it was causing unexpected results

MAP-2636 clear flash before saving new values

---

package.json
server/config/edit/incidentDetailsConfig.ts
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/services/editReports/incidentDetails.test.ts
server/services/editReports/incidentDetails.ts
server/services/editReports/types/reportEditServiceTypes.ts
server/services/index.ts
server/services/reportEditService.test.ts
server/services/reportEditService.ts
server/services/reportService.test.ts
server/services/reportService.ts
server/utils/utils.test.js
server/utils/utils.ts

[MAP-2636](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-2636)
This PR 
- persist edits of incident-details to the current report 
- refactors/deletes utility methods
[MAP-2636]: https://dsdmoj.atlassian.net/browse/MAP-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Map 2636 uof edit incident details persist edits to report

---

integration-tests/integration/coordinator/edit-report/incident-details.cy.js
integration-tests/pages/coordinator/editHistoryPage.js
integration-tests/pages/coordinator/incidentDetailsPage.js
integration-tests/pages/coordinator/reasonForChangePage.js
integration-tests/pages/coordinator/viewIncidentPage.js
integration-tests/pages/page.js
server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/routes/viewingIncidents/viewIncidents.ts
server/services/reportEditService.ts
server/views/pages/coordinator/reason-for-change.njk
server/views/pages/coordinator/relocation-and-injuries.njk
server/views/pages/viewIncident/incident.njk

PR for [MAP-2636](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&isEligibleForUserSurvey=true&selectedIssue=MAP-2636)
- add prisoner profile and back link to edit/incident-details
- add prisoner profile and back link  to /reason-for-edit
- add success banner to view/incident
[MAP-2636]: https://dsdmoj.atlassian.net/browse/MAP-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-2636 add success banner, add prisoner-profile, correct back links

---

integration-tests/integration/coordinator/edit-report/incident-details.cy.js
server/config/edit/reasonForChangeErrorMessageConfig.ts
server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/services/reportEditService.test.ts
server/services/reportEditService.ts
server/views/pages/coordinator/reason-for-change.njk
server/views/pages/viewIncident/edit-history.njk

- make additional info text mandatory 
- correct error messages
- ensure any previously selected radios and entered text are redisplayed following error message alerts

MAP-2781 reason for change page
