ministryofjustice/use-of-force

server/config.js

Dropping timeouts as these requests could now be retried twice meaning a pause of 90 seconds. This drops the time a client may have to wait, down to 30 seconds

Drop timeouts

---

.eslintignore
.gitignore
README.md
cypress.json
docker-compose.test.yml
integration-tests/.eslintrc
integration-tests/db/db.js
integration-tests/integration/createIncident/login.spec.js
integration-tests/mockApis/auth.js
integration-tests/mockApis/elite2api.js
integration-tests/mockApis/wiremock.js
integration-tests/pages/newIncidentPage.js
integration-tests/plugins/index.js
integration-tests/support/commands.js
integration-tests/support/index.js
package-lock.json
package.json
server/app.js
server/views/formPages/incident/newIncident.html
server/views/pages/index.html

These tests currently require a wiremock instance running to stub out auth/elite2. 
There is a docker-compose file which sets one up for development purposes.
Haven't integrated into circle ci yet - after speaking to Matt, intending to start wiremock as a separate task (`java -jar wiremock.x.jar`) before running tests, rather than a separate container as containers are a limited resource.

DCS-46 Adding cypress tests

---

README.md
cypress.json
package.json

Allow restarting the service during development on template changes.
Only record cypress videos when tests fail

Fixing nodemon

---

server/views/formPages/incidentMacros.njk

A HTML validation check revealed we can not place H1's inside legends.
The Govuk components do however allow them but only if the H1 represents the page header.
This would happen if there is one question per page and the header and question are the same.
In the UoF pages we have multiple questions on each page hence I have removed the H1s leaving the legend to represent the question for the relevant input component.

DCS-52 bugfix to remove H1's from legends

---

integration-tests/integration/createIncident/enter-initial-details.js
server/config/incident.js
server/routes/form.js
server/services/formService.js
server/services/formService.test.js

Adding the ability to specify sanitisers as part of the field config
The specific sanitisers required were:
* Ensure that numeric ids are stored as ids
* Filtering out empty rows for add another staff and witnesses

DaCS-37 Sanitising input

---

package.json
server/views/formPages/incident/details.html
server/views/formPages/incidentMacros.njk

http://localhost:3000/form/incident/details/-35
The Details page was saving user selections to DB but if user navigated back to the same page,
their previous selections were not being presented.
There is a global object called data that holds all the selection info so have used that inside incidentMacro.njk and
tested it against the value property in details.html to display the previous selections.

DCS 52: Users selections repopulated when moving between pages

---

integration-tests/integration/createIncident/enter-initial-details.js
integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/pages/checkAnswersPage.js
integration-tests/pages/newIncidentPage.js
integration-tests/pages/page.js
server/routes/checkAnswers.js
server/views/formPages/incident/newIncident.html
server/views/pages/check-answers.html

Fixed a couple of bugs:
* When a sole witness or staff member were persisted - when we re-visited the page
the remove button was present. If that remove button was pressed we couldn't add
another entry
* When no witnesses or staff members were persisted, we would get a null pointer
when trying to persist the form again
Also test to ensure that we can render pre-saved data

DCS-37 Fixing bugs and improving tests

---

server/app.js
server/authentication/auth.js
server/authentication/clientCredentials.js
server/authentication/clientCredentials.test.js
server/authentication/signInService.js
server/authentication/signInService.test.js
server/utils/fiveMinutesBefore.js
server/utils/fiveMinutesBefore.test.js

Token refresh was not implemented - but there was some code which attempted to redirect to login 5 minutes before the token expired (Not quite sure why).
The redirect would always be intercepted by the same code, so an infinite redirect loop would occur.
I've fixed this by back porting token refreshing functionality from categorisation tool.

DCS-60 Fixing redirect loop & adding token refreshing

---

integration-tests/db/db.js
integration-tests/integration/createIncident/enter-initial-details.spec.js
integration-tests/integration/createIncident/form-submit.spec.js
migrations/20190726000000_form_db.js
package-lock.json
package.json
server/app.js
server/config/fieldType.js
server/config/incident.js
server/data/formClient.js
server/data/formClient.test.js
server/routes/checkAnswers.js
server/routes/form.js
server/routes/incidents.test.js
server/services/incidentService.js
server/services/incidentService.test.js
server/services/updateBuilder.js
server/services/updateBuilder.test.js

Several changes to the data layer: 
* Renaming form service to incident service (and renaming associated tables)
* renaming incident start_date to created_date
* Storing incident date separately from json payload
* Storing staff involved in an incident in separate table

DCS-64 Refactoring incident persistence

---

integration-tests/pages/checkAnswersPage.js
integration-tests/pages/relocationAndInjuriesPage.js
server/routes/checkAnswers.js
server/views/formPages/incident/evidence.html
server/views/formPages/incident/relocationAndInjuries.html
server/views/formPages/incidentMacros.njk
server/views/pages/pagesMacros.njk

http://localhost:3000/form/incident/relocationAndInjuries/-1
http://localhost:3000/form/incident/evidence/-1
Ran the Relocation and Injuries and Evidence pages through HTMLM validator. It revealed unnecessary definition of rows and columns for textareas, missing divs and missing id attribute. Corrected erorrs and rechecked. Updated Cypress tests.

DCS-56 and 61 Fixed HTML validation errors

---

integration-tests/pages/checkAnswersPage.js

The Cypress tests previously generated a regex of the date and time for the test. Unfortunately rather than generating DD/MM/YYY and HH:mm, it actually generated the current date and time, eg 05/08/2019 and 13:47.
This meant that although the tests were passing they were doing so on an incorrect basis.
So have revised the regex and used the invoke('trim'), which is just like Jquery's trim () function, to remove any hidden characters before and after the date and time

DCS-74: Date and time should have correct format

---

assets/sass/application-ie8.sass
assets/sass/application.sass
package-lock.json
package.json
server/app.js
server/utils/nunjucksSetup.js
server/views/formPages/formTemplate.html
server/views/formPages/incident/details.html
server/views/formPages/incident/evidence.html
server/views/formPages/incident/newIncident.html
server/views/formPages/incident/relocationAndInjuries.html
server/views/formPages/incidentMacros.njk
server/views/pages/check-answers.html
server/views/pages/incidents.html
server/views/pages/statement/provide.html
server/views/pages/statement/submitted.html
server/views/pages/submitted.html
server/views/partials/header.html
server/views/partials/layout.html

Application upgraded from govuk-frontend toolkit v2.12.0 to 3.0.0
Required paths to be suffixed with /govuk and for data-module attributes to be prefixed with govuk. See https://github.com/alphagov/govuk-frontend/releases

DCS-70-upgrade-govuk-frontend-tollkit-to-3.0.0

---

server/data/authClientBuilder.js
server/data/authClientBuilder.test.js
server/data/elite2ClientBuilder.test.js
server/index.js
server/routes/incidents.js
server/services/userService.js
server/services/userService.test.js

This is not currently hooked up to anything and also does not take into account users
which exist in nomis but not new-nomis.
(For the alpha we can ensure all users will exist in new-nomis but will ticket up this limitation)
It groups usernames into those that have verified email address, those that don't and those that
don't exist. We'll use these groups and the success flag to determine whether we can persist the
data and how to display validation messages if we can't

DCS-38 Adding ability to retrieve emails for usernames

---

server/config/evidenceValidation.test.js
server/config/incident.js
server/utils/fieldValidation.js
server/views/formPages/incident/evidence.html

Adding ability to link errors to individual array items when multiple values can be input via add-another component. 
Also allowing focusing on the first field of the first item when there is something wrong with the overall structure of an array. 
Also adding validation tests
We currently display the same message for each invalid item: 
<kbd>
</kbd>
So although the links now work and point to the correct item - we will need some content updating (and a way to get access to the index which might be a bit gnarly...)

DCS-86 adding ability to link errors to individual array items

---

assets/js/add-another.js
server/config/evidenceValidation.test.js
server/config/incident.js
server/config/types.js
server/views/formPages/incident/evidence.html

http://localhost:3000/form/incident/evidence/-1
Validation failure (when an input either hasn't been selected or left empty) now generates a validation error message.
In cases where radios have  nested text inputs, the first message is for the component as a whole. If the user has then selected Yes but hasn't input anything into the nested text field then that generates another error message.
A couple of issues have been identified: 1) where the user clicks  Add Another and the current input is already highlighted with an error, the newly created input field also has error highlighting and 2) each Added input field (and any subsequent error messages) need to be distinguishable from the previous input, perhaps by the use of an index in the input's label. These 2 issues will be done as new …

DCS-86: Validation messages for Evidence page

---

integration-tests/integration/createIncident/submit-statement.spec.js
integration-tests/pages/incidentsPage.js
integration-tests/pages/viewStatementPage.js
server/config/statement.js
server/config/statementValidation.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/utils/fieldValidation.js
server/views/pages/statement/confirm.html
server/views/pages/statement/provide.html
server/views/pages/statement/review.html

Always persistng statement on submit - even if valdiation fails.
This means that a user can comeback to their work later and we can avoid issues with trying to store large amounts of content in cookie sessions.
Not carrying out validation when the user click save and return to incident list.

DCS-75 Adding validation to statement page

---

integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/submit-statement.spec.js
server/config/detailsValidation.test.js
server/config/evidenceValidation.test.js
server/config/incident.js
server/utils/fieldValidation.js
server/views/formPages/incident/details.html
server/views/formPages/incidentMacros.njk

http://localhost:3000/form/incident/details/-1
The Details page didn't previously validate user inputs. Have now ensured validation massages are presented should a user fail to either make a selection of radio/checkbox or fail to input details in text boxes.
User is unable to proceed to another page if validation rules are not met.
New unit tests created and have also made minor changes to the validation messages in the Evidence page.
Minor changes to HTML in incidentMacros.njk to make W3C compliant

DCS 84: Details page displays error messages following field validation

---

server/config/incident.js
server/config/incidentDetailsValidation.test.js
server/services/reportStatusChecker.js
server/services/reportStatusChecker.test.js
server/utils/fieldValidation.js
server/utils/fieldValidation.test.js
server/views/formPages/incident/incidentDetails.html

This checks that each section of a report is complete and reports back either:
COMPLETE, INCOMPLETE or NOT_STARTED
This will then be used to determine whether to show the 'check your answers' page
and also to ensure that we can do a checkState when submiting a report.
Also making involved staff optional as this now refers to staff other than the
reporting officer. (If the use of force only involved the reporter than no other staff
would be entered)
Also adding a bit of an extra check to ensure that users cannot add involved staff
details through nefarious means.

DCS-100 Adding a report status checker

---

integration-tests/integration/createIncident/save-additional-comment.spec.js
integration-tests/pages/viewStatementPage.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.js
server/services/statementService.js
server/services/statementService.test.js
server/views/pages/incidents.html
server/views/pages/statement/your-statement.html

New functionality to take user's inputs in UI and persist to db.
User can navigate to the incident statement by clicking the View and Amend button on http://localhost:3000/
User can then input any additional details in the text box. Clicking the Save additional comments button persists new entry to db and redirects user back to the same screen. 
The additional comments are linked to the original statement via the statement.id value
Testing not yet included

DCS-78 - Users additional comments being persisted to db

---

server/routes/checkYourAnswers.js
server/routes/checkYourAnswers.test.js
server/routes/createReport.js
server/routes/createReport.test.js
server/services/reportService.js
server/utils/utils.js
server/utils/utils.test.js
server/views/formPages/incident/incidentDetails.html

This would previously go to check-your-answers but now we are restricting the
check your answers page if the whole form is not valid.
Now, if the form is not complete, then submitting from the evidence page will
redirect the user back to the main task list page.
Also adding missing hint text for involved staff

DCS-113 Fixing submit location from evidence page

---

job/reminders/reminderPoller.js
job/reminders/reminderPoller.test.js
job/reminders/reminderSender.js
job/sendReminders.js
migrations/20190903000000_form_db.js
package.json
server/data/dataAccess/db.js
server/data/incidentClient.js
server/data/incidentClient.test.js

Using [this](https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/) mechanism for creating a work queue of outstanding reminders over the statement table.
Still need to do the code to actually process the reminder.
This will currently log the first reminder 100 times on each job poll (every 5 minutes) as still need to mark each reminder so it won't be picked up again.

DCS-93 Adding polling of a reminder queue

---

job/reminders/reminderSender.test.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/services/reportService.js
server/services/reportService.test.js

This seeds the initial next reminder date when the report is submitted.
The initial reminder date is the submitted date plus one.
Also fixing an issue where we weren't returning incident date as part
of the reminder item which meant the email template was defaulting
incident date and time to 'now'

DCS-93 seeding initial next reminder date

---

job/reminders/reminderSender.js
job/reminders/reminderSender.test.js

We weren't passing through submitted date so we were calculating the deadline date based on 'now'
Fixed this and added some better tests.
Removed where we were incorrectly passing through submitted date for overdue reminders.

DCS-93 correcting email template variables

---

migrations/20190913000000_form_db.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/middleware/authorisationMiddleware.test.js
server/services/reportService.js
server/services/reportService.test.js

To allow us to filter by agencies that reviewers are allowed to see
Also adding an updated_date to reports and setting when updating reports. 
Putting in place an overdue date column on statements which will allow us to easily query if statements are overdue or not

DCS-129 Storing agency on the report level

---

server/views/pages/your-report.html

To apply standard govuk-body font class to elements in View Report page

DCS-141: use govuk-body font class

---

server/config/incident.js
server/utils/fieldValidation.js

Removing looking up of error messages as this is done already:
`getIn([error.path[0], 'validationMessage', error.type], fieldConfig)`
Extracting out name regex - this helps as we can see that we are using the same pattern in multiple places
Also if we need to change it -we just need to change one place
Also escaping '-' as it's in a character class

DCS-116 Tidying up validation

---

integration-tests/db/db.js
job/reminders/reminderSender.js
job/reminders/reminderSender.test.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/middleware/authorisationMiddleware.test.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/services/notificationService.js
server/services/notificationService.test.js
server/services/reportService.js
server/services/reportService.test.js

Storing at creation rather than having to derive what it is later. This will make it easier to query whether a statement is overdue in queries and simplifies the reminder sending a bit.

DCS-129 Storing overdue date on statement creation

---

integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/createIncident/mark-reports-as-complete.spec.js
integration-tests/integration/createIncident/view-all-incidents.spec.js
integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/integration/createIncident/view-your-reports.spec.js
integration-tests/integration/statements/save-additional-comment.spec.js
integration-tests/integration/statements/submit-statement.spec.js
integration-tests/pages/allIncidentsPage.js
integration-tests/pages/statementSubmittedPage.js
integration-tests/pages/yourStatementsPage.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/index.js
server/middleware/authorisationMiddleware.test.js
server/routes/incidents.js
server/services/reportService.test.js
server/services/statementService.js
server/services/statementService.test.js
server/views/pages/statement/statement-submitted.html

Once all statements are complete, we need to mark the report as complete
This will mean that reviewers will be able to see the report in their
completed list.
Having to change the getreports query as once a report is complete, it
then would disappear from the reporters list of completed reports

DCS-129 marking report as complete

---

integration-tests/integration/statements/submit-statement.spec.js
server/routes/statements.js
server/views/pages/statement/write-your-statement.html
server/views/partials/layout.html

The content is still the same as before. The only differences are:
1, the Year field for joining Prison Service has been dropped to a new row below the month and Year of Refresher training
2, have removed the hardcoded h1 title and pushed the page title from the back-end into both the current page and the layout.html. This will cause the browser tab to also displays the page title.

DCS-126: Top half of Write UOF statement reformatted

---

server/routes/reportUseOfForce.js
server/views/formPages/incident/evidence.html
server/views/formPages/incident/incidentDetails.html
server/views/formPages/incident/relocationAndInjuries.html
server/views/formPages/incident/useOfForceDetails.html
server/views/formPages/incident/username-does-not-exist.html
server/views/pages/check-your-answers.html
server/views/pages/error.html
server/views/pages/report-sent.html
server/views/pages/report-use-of-force.html
server/views/pages/statement/add-comment-to-statement.html
server/views/pages/statement/check-your-statement.html
server/views/pages/statement/statement-submitted.html
server/views/pages/statement/write-your-statement.html
server/views/pages/statement/your-statement.html
server/views/pages/your-report.html
server/views/partials/incidentPage.html
server/views/partials/layout.html

The browser tab was a generic GOV.UK statement previously. Have now matched it to the title of the page the tab relates to.
Have applied a generic tab message of 'GOV.UK - Use of force' as a default should there ever be a page where the title isn't set using Nunjucks

DCS-115: Browser page tab displays the same message as page title

---

server/routes/statements.js
server/routes/statements.test.js
server/views/pages/statement/your-statement.html

Navigation around viewing statements and adding comments did not really make sense for reviewer as in a few places it was redirecting to `/` - which for reviewers means `/all-incidents`.
These have been changed to /your-statements as the user will be in viewing and modifying statements mode.

DCS-151 Correcting navigation around statements

---

integration-tests/integration/reportPages/check-your-answers.spec.js
integration-tests/integration/reportPages/enter-use-of-force-details.spec.js
integration-tests/pages/checkAnswersPage.js
integration-tests/pages/detailsPage.js
integration-tests/pages/evidencePage.js
integration-tests/pages/newIncidentPage.js
integration-tests/pages/relocationAndInjuriesPage.js
integration-tests/pages/tasklistPage.js
package.json
server/config/types.js
server/routes/createReport.js
server/routes/createReport.test.js
server/routes/index.js
server/views/formPages/formTemplate.html
server/views/formPages/incident/username-does-not-exist.html
server/views/pages/pagesMacros.njk
server/views/pages/reportDetailMacro.njk

Generally navigation through the form follows a linear path:
tasklist -> incident-details -> uof-details -> r-and-i -> evidence -> check-answers
If you select a link from the tasklist page then you can drop in the linear journey at any point, e.g::
tasklist -> r-and-i -> evidence -> check-answers
Previously, the edit links on check-your-answers would do the same. 
This change alters this so if you click save after visiting a form from the check-your answers it will redirect you back to check-your-answers.
If you click cancel from any form, visited from check-your-answers it will just take you back to check-your-answers without persisting anything
This is more complicated if you select to do this for incident details as we need to ensure that all the users are valid and present the …

DCS-119 Add edit navigation to check-your-answers

---

integration-tests/integration/reportPages/enter-incident-details.spec.js
integration-tests/integration/reportPages/enter-use-of-force-details.spec.js
integration-tests/pages/page.js
server/routes/createReport.js
server/views/formPages/formTemplate.html
server/views/formPages/incident/username-does-not-exist.html
server/views/pages/check-your-answers.html
server/views/pages/report-sent.html
server/views/pages/reviewer/view-report.html
server/views/pages/reviewer/view-statements.html
server/views/pages/your-report.html

Have removed the back links from every page in the application that used them. This was needed because a loop was occurring where the back link alternated between current and previous page rather than traversing the complete browser history.
Cypress tests updated by removing  the function "back: () => cy.get('.govuk-back-link')" and replaced references to "*.back().click()" with Cypress' default of cy.go('back') as it does the same thing.

DCS-49: Back links removed, Cypress tests updated

---

assets/sass/local.sass
assets/sass/palette.sass

The blue section was previously slightly taller than the surrounding black bar so have reduced its height. Have also chaned the layout when screen is Samsung S5 sized. The only 2 screen sizes needed to be considered for are Samsung S5 and desktop
Note have changed the blue colour to shade #015ea5 to be consistent with DPS. Could not find a sass code equivalent to #015ea5 in the latest GDS toolkit hence have used the hex code

DCS-160: fixed blue section in page header

---

server/routes/api.js
server/routes/api.test.js
server/routes/testutils/appSetup.js

We want to limit people reviewing reports to only be able to see information about their active caseloads.
This means we can prevent them from viewing data they should not be able to see and also simplifies the frontend

DCS-192 Deriving agency id by active caseload

---

server/data/incidentClient.js
server/data/incidentClient.test.js

This should be report submitted date rather than statement submitted date.
This is currently showing "Invalid date" in the email content so reverted the email templates back to refer to incident date until we get this released.

DCS-179 Correcting submission date 

---

integration-tests/db/db.js
server/app.js
server/data/incidentClient.js
server/data/incidentClient.test.js
server/data/statementsClient.js
server/data/statementsClient.test.js
server/index.js
server/routes/api.js
server/routes/api.test.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/services/statementService.js
server/services/statementService.test.js

We have already received 5 requests to add involved staff members to a report as they
were missed when the report was raised.
We have worked out a process to do this but its fiddly, easy to get wrong and very time consuming.
It also involves manually running db statements.
The idea is to add the ability for coordinators to be able to do this through the
application which will require input from design and additional time (We have a ticket on the backlog for this).
As a temporary fix, this change adds an endpoint that can be called by internal staff to add
these member easily.
We don't have any auth setup for api style endpoints so I've made this easy to trigger from
a browser as a logged in user.

DCS-223 Adding temporary endpoint to add missed staff

---

server/data/authClientBuilder.js
server/data/authClientBuilder.test.js

It is is possible to add an invalid member of staff by passing a username in the invalid case.
The staff lookup performs a case insensitive look up but we end up persisting the user provided value.
When we retrieve statements for the current user, we will do a case sensitive lookup based on the current username.
It is likely that the two versions of the usernames don’t match up.
This changes it so that we always persist the service provided username

DCS-320 Fix adding broken involved staff

---

helm_deploy/secrets-example.yaml
helm_deploy/use-of-force/templates/_envs.tpl
helm_deploy/use-of-force/templates/secrets.yaml
integration-tests/mockApis/elite2api.js
server/app.js
server/config.js
server/data/authClientBuilder.js
server/data/authClientBuilder.test.js
server/data/elite2ClientBuilder.js
server/data/elite2ClientBuilder.test.js
server/index.js
server/routes/api.js
server/routes/api.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.js
server/routes/statements.js
server/routes/statements.test.js

Previously the prisoner name would go missing if the prisoner moved to a caseload that wasn't in the user's list.
This also fixes a similar issue when a prisoner is released.
All these places where we use the system token don't allow injecting a booking id directly - they only load a prisoner referenced from a report that belongs to the current user (or any user on any report if a reviewer).

DCS-249 Fixing issue where offender moves after a report is created.

---

server/app.js
server/data/authClientBuilder.js
server/data/authClientBuilder.test.js
server/middleware/authorisationMiddleware.js
server/middleware/authorisationMiddleware.test.js
server/routes/api.js
server/routes/api.test.js
server/routes/coordinator.js
server/routes/coordinator.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.js
server/routes/statements.js
server/routes/testutils/appSetup.js
server/views/pages/coordinator/confirm-deletion.html
server/views/pages/reviewer/view-report.html

A delete button appears on the view-report screen if the current user is a coordinator.
This goes to a confirmation page and clicking the button there will trigger soft delete which redirects to the home page.
Need to get content folk to look at it and suggest better text/interaction design.
Also fixing new system token bug - was trying to read an unknown property called token from the token (rather than access_token)

DCS-336 Adding frontend to allow coordinators to soft delete reports

---

server/app.js
server/routes/api.js
server/routes/api.test.js
server/routes/checkYourAnswers.js
server/routes/checkYourAnswers.test.js
server/routes/coordinator.test.js
server/routes/createReport.js
server/routes/createReport.test.js
server/routes/index.js
server/routes/reportUseOfForce.js
server/routes/reportUseOfForce.test.js
server/routes/testutils/appSetup.js
server/services/reportService.js
server/services/reportService.test.js

Currently a user is prevented from continuing to complete a report if the offender leaves the current prison.
This change will allow users to always see offender details if the report already exists.
(We need to prevent prison officers from seeing offender details if they do not exist in the current establishment)
This will also enable the posibility of a monitored process that will create a draft report for a prisoner that has
already left an establishment (potentially by a coordinator). The reporter will be able to continue the draft without
being given access to other caseloads.

DCS-376 Allow user to alway complete reports

---

.circleci/config.yml
helm_deploy/use-of-force/templates/job.yaml
helm_deploy/use-of-force/templates/monitoring.yaml

Altering job to use the replace concurrency policy. This should kill an existing job if it lasts longer
than the next scheduled start time and start a new pod.
Also setting a deadline to ensure that the job ends if it lasts longer than 4 minutes
(The job runs every 5 minutes and processes up to 50 reminders which is generally very fast)
Also adding 2 prometheus checks:
1.) to check that the previous schedule time was less than 10 minutes
2.) to check that no recents jobs failed

DCS-387 Adding monitoring and tweaking job

---

job/reminders/emailResolver.js
job/reminders/emailResolver.test.js
job/reminders/reminderPoller.js
job/reminders/reminderPoller.test.js
job/reminders/reminderSender.js
job/reminders/reminderSender.test.js
job/sendReminders.js

We only send a reminder for the first 3 days that a staff member hasn't filled in their statement.
After that we send an overdue email and exclude that item from future polling.
For unverified users we weren't excluding them from being claimed by the polling process after they were overdue.
Simplified the poller a bit, by not explicitly handling newly verified users and instead allowing them to be naturally be picked up on the next poll
Also fixing issue where picking up an unverified user would prematurely stop the polling. Now unverified users are excluded from polling stats but do not lead to the poller to think that all reminders have been processed

DCS-374 Tidying up job and fixing issue around overdue unverified users

---

server/data/incidentClient.js
server/data/incidentClient.test.js
server/routes/createReport.js
server/routes/createReport.test.js
server/services/offenderService.js
server/services/offenderService.test.js

This change ensures that we only retrieve internal locations from the establishment where
the incident occured, rather than the establishment that the offender currently is.
The internal location list is only needed when the draft report is being filled out but
if creating a report for an offender who has recently left prison this distinction is
important.
This change also removes loading location list when unnecessary - we previously retrieved
the list every time we accessed the offender details.

DCS-394 Ensure retrieve correct incident location list

---

integration-tests/db/db.js
integration-tests/integration/coordinator/add-involved-staff.spec.js
integration-tests/integration/coordinator/remove-involved-staff.spec.js
integration-tests/pages/reviewer/addInvolvedStaffPage.js
integration-tests/pages/reviewer/addInvolvedStaffResultPage.js
integration-tests/pages/reviewer/allIncidentsPage.js
integration-tests/pages/reviewer/viewReportPage.js
migrations/20200311000000_form_db.js
server/index.js
server/middleware/roleCheck.js
server/middleware/roleCheck.test.js
server/routes/coordinator.js
server/routes/coordinator.test.js
server/routes/incidents.js
server/routes/incidents.test.js
server/routes/index.js
server/services/involvedStaffService.js
server/services/involvedStaffService.test.js
server/views/pages/check-your-answers.html
server/views/pages/coordinator/add-involved-staff/add-involved-staff.html
server/views/pages/coordinator/add-involved-staff/already-exists.html
server/views/pages/coordinator/add-involved-staff/missing.html
server/views/pages/coordinator/add-involved-staff/unverified.html
server/views/pages/reportDetailMacro.njk
server/views/pages/reviewer/view-report.html
server/views/pages/your-report.html

If a new staff member is added to a completed report it will mark the report as incomplete.
Staff are added via the report details screen:
<kbd>![Screenshot 2020-03-12 at 16 02 31](https://user-images.githubusercontent.com/1517745/76541070-ec367100-647a-11ea-8312-90ebb2b182f4.png)</kbd>
One a user has been added they will be presented the "view report" screen.
There are 3 different error cases that are handled and present an interrupt screen with an appropriate message:
1.) The user does not exist: will lead the user back to 'add another user' screen to try again
2.) The user is already on the report: will lead the user back to "view report"
3.) The user is unverified: this adds the user to the report and will redirect to 'view report'
Also needed to fix a unique index on statements which …

Adding ability for coordinators to add missing staff to reports

---

integration-tests/integration/reportPages/check-your-answers.spec.js
server/routes/checkYourAnswers.test.js
server/routes/model/reportSummary.js
server/services/reportStatusChecker.test.js

The 'Was prisoner compliant?' question in check-your-answers has been changed so that it's answer is only capitalised on the first letter. Previously, if the answer began with a 'No', then the content atfer that started with a capital. This is no longer the case.

DCS-236-changes to font

---

server/data/reportingClient.js
server/data/reportingClient.test.js
server/routes/api.js
server/routes/api.test.js
server/services/reportingService.js
server/services/reportingService.test.js

This returns summary information for all submitted Incidents that were submitted within a
specific month.
Waiting to here back whether we want to key by incident date instead but there are some
disadvantages that way based on getting incomplete reports at the end of the month.
Also moving to use new role based middleware rather than having custom authorisation within
the routes

DCS-200 Adding new incident overview report

---

package-lock.json
package.json

I think this might have been included in node-sass-middleware and only required by app insights - so it got all the way until attempting to deploy to dev before failing

DCS-429 Fixing missing request library preventing app from starting up in dev

---

package.json

Increases run time from 14 seconds to 19 on my laptop.  Seems to take rather longer on CircleCI - but not as long as the integration tests (surprise), so it doesn't really matter.

DCS-196: Run Jest tests 'in band' to reduce memory use on CircleCI.

---

server/services/offenderService.test.ts
server/services/offenderService.ts

The UOF report incident-details page has a select input for Incident location.
This PR is to ensure that should there be any locations called Prisoner's Cell or Other cell, they are at the top of the select options.
Any subsequent options will be in alpha order

Dcs 424 sort prisoner and other cell

---

server/services/userService.js
server/services/userService.test.js

If an unverified user is added then the system was storing
the user provided version of the username.
This causes an issue where elite2 and auth use case insensitive search so
return results correctly but we then cannot load their statement as we do a case
sensitive search on statements by user id.
We'd rather store the user ids in the canonical form so upper casing here.

DCS-472 Fix issue adding unverified users

---

server/views/partials/incidentPage.html

Adding an additional exit link to incident list pages. 
<kbd>
</kbd>
This is possibly an interim measure as we workout how to effectively display the home page.

DCS-467 Add exit link to top of the page.

---

server/views/tagManager/headContent.html

Extend the Google Tag Manager header include to introduce the dataLayer javascript variable and add the activeCaseloadId value to the dataLayer. Google Tag Manager and Analytics can then be configured to capture this value as part of every hit.

DCS-483 Tag 'submit a report'. 

---

assets/sass/local.sass
server/views/pages/statement/write-your-statement.html

Removed gap between Prisoner and date of Incident two elements.
Select for month made bigger so it can fit months that have longest spelling.

DCS-439: layout changes

---

server/views/formPages/formTemplate.html
server/views/formPages/incident/incidentDetails.html
server/views/macros.njk

and reducing incident details page to 2/3rds
<kbd>
</kbd>
The change to the save draft button appears on all pages in the main create report flow

DCS-448 Moving to use new submit link macro 

---

assets/sass/local.sass
server/views/pages/report-sent.html
server/views/pages/reportDetailSectionsMacros.njk
server/views/pages/reviewer/view-statements.html

Report sent page: Change grey button text to 'Exit to Digital Prison Services
`{/bookingId}/view-report` 
Expand the width of the label section so that, where possible, it remains on a single line
The playback of incident details at the top should have reduced line spacing so that it aligns with the ‘view report’ page
It matches the layout for DCS-444 (above) now.

DCS-438, DCS-444, DCS-445

---

server/routes/statements.js
server/routes/statements.test.js

Should always open 'your statements' tab, this currently opens `/` which means that reviewers and coordinators get sent to `All incidents` instead. 
<kbd>
</kbd>
This was fixed for 'review your statement" but not explicitly covered by a ticket and should be consistent

DCS-545 Fixing link location for reviewers/coordinators

---

server/views/pages/reviewer/view-statement.html
server/views/pages/statement/check-your-statement.html
server/views/pages/statementDetailMacro.njk

screen shots of pages impacted
1. check-your-statement
<bkr>
</bkr>
2. your-statement
<bkr>
</bkr>
3. your-statement with added comments
<bkr>
</bkr>
4. view statement. As see by coordinator 
<bkr>
</bkr>

DCS-437: layout changes to view-statement

---

server/views/pages/your-statements.html

view-statement link is now in line with other content in the row
<bkr>
</bkr>

added 15px padding-top to link

---

integration-tests/integration/createIncident/form-submit.spec.js
integration-tests/integration/reviewer/view-completed-incidents.spec.js
integration-tests/pages/reviewer/completedIncidentsPage.js
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/routes/reviewer.test.ts
server/routes/reviewer.ts
server/services/reviewService.test.ts
server/services/reviewService.ts
server/utils/page.test.ts
server/utils/page.ts
server/views/pages/completed-incidents.html

As we don't store prisoner names in the service, if people search by prisoner name then we have to load up all records that match the rest of the criteria, attached the names and then filter by prisoner name and page in memory. Otherwise we would end up with odd shaped pages
If not explicitly searching by prisoner name then we fallback to just doing a normal paginated search

DCS-572 Adding pagination for completed incidents

---

assets/sass/local.sass
server/views/formPages/incident/incidentDetails.html
server/views/formPages/incidentTimeMacro.njk
server/views/formPages/timeMacro.njk

The macro has been trimmed down to remove any unused elements. The incidentsDetails.html file uses this macro so that has been updated to pass in only the dynamic content (value and error classes). All the other classes and attributes for the hour and minute has been hard coded into the macro.
Have added a new class to widen the date input field because when there is an error in the date, the red errors border covers some of the field content.
Screen shot of errors below
<bkr>
</bkr>

DCS-618: timeInput macro refactored

---

server/config/forms/incidentDetailsForm.js
server/config/forms/incidentDetailsValidation.test.js
server/config/incident.js
server/index.js
server/routes/checkYourAnswers.js
server/routes/checkYourAnswers.test.js
server/routes/createReport.ts
server/routes/incidentDetails.ts
server/services/involvedStaffService.test.ts
server/services/involvedStaffService.ts
server/services/report/draftReportService.ts
server/services/report/reportStatusChecker.js
server/services/report/reportStatusChecker.test.js
server/services/report/submitDraftReportService.test.ts
server/services/report/submitDraftReportService.ts
server/services/report/updateDraftReportService.ts
server/services/reportDetailBuilder.test.ts
server/services/reportingService.test.ts
server/services/reportingService.ts
server/types/uof.d.ts

Previously we would prevent a user from submitting a report if they
had listed users in the report that didn't exist in nomis.
This was to handle an edge case where the user failed to resolve
a missing user after being prompted.
Going forward there will be no way to add a missing staff member so
this check will not be necessary. Implementing this change now
to ease moving to new flow. 
In the meanwhile we will automatically remove missing users for the user
(which should be fine as the user will have had to navigate away after being presented a warning message)

DCS-403 Removing missing user check

---

assets/sass/local.sass
server/views/pages/reviewer/view-statement.html
server/views/pages/statement/add-comment-to-statement.html
server/views/pages/statement/check-your-statement.html
server/views/pages/statement/your-statement.html
server/views/pages/statementDetailMacro.njk

http://localhost:3000/{reporttId}/your-statement
The user can print the statement currently on view.
The first section of the page (Prisoner, Date of incident, LastControl etc) has been changed from
being laid in 2 x 2 to being vertically stacked. The print link has been placed on the extreme
top right of the content section. Because the print link is outside of the 2/3rds content width,
the horizontal rules have been extended to full width but just for the you-statement page.
Other pages that use the statementDetail macro still have their horizontal rules at 2/3rds width
<img>
</img>
<img>
</img>

DCS-614: user can print statement

---

server/views/pages/statement/your-statement.html
server/views/pages/statementDetailMacro.njk

http://localhost:3000/{reportId}/your-statement
The information in the top part of the page is now in blocks rether then tight upto each other.
More consistent spacing between statement and additional comments
This ticket corrects mistakes made previously that had been pushed to main. The mistake was, the data in the header section of the print was incorrect
Have also moved code from the print section on your-statement to statementDetailMacro.detail

DCS-614 user can print off their statement

---

assets/sass/local.sass
server/routes/reviewer.ts
server/views/pages/reportDetailMacro.njk
server/views/pages/reportDetailSectionsMacros.njk
server/views/pages/reviewer/view-statements.html

Corrodinator/Reviewer can print both the report and statements (plus added comments ) in one go from the 
/view-statements page
Screen shot 1: page before any changes (from T3)
screen shot 2 : page after code change
screen shot 3, 4 and 5 show the print preview (top, middle and bottom)

Dcs 630 uof reviewer/coordinator can print report and its statement

---

server/app.js

This is a middleware that is added by default version 4.0 of helmet. This prevents running of js unless it's specifically accounted for as part of the security policy which breaks everything. 
Added a ticket to the backlog to get it working under CSP

DCS-640 Remove content security policy. 

---

server.js
server/app.ts
server/data/reportingClient.test.ts
server/data/reportingClient.ts
server/index.js
server/index.ts
server/routes/api.js
server/routes/api.test.js
server/routes/changePrison.test.ts
server/routes/coordinator.test.ts
server/routes/incidents.test.ts
server/routes/index.ts
server/routes/reportUseOfForce.test.ts
server/routes/reviewer.test.ts
server/routes/statements.test.ts
server/routes/testutils/appSetup.ts
server/services/index.ts
server/services/involvedStaffService.ts
server/services/prisonerSearchService.ts
server/services/reportingService.test.ts
server/services/reportingService.ts
server/types/uof.d.ts

Separating out a service index.ts which does the service wiring up from
the creation of the app.
The type for the services container can then be passed straight through to the routers
rather than threading through each service independently.
This had a knock on effect of forcing tests to be tidied up a bit
Also moving reporting client over to class.

DCS-640 Tidying up application creation

---

server/views/formPages/formTemplate.html

These links all go to the "Report use of force" page so do not need the incidents suffix

DCS-663 correcting link

---

assets/sass/local.sass
server/views/formPages/incident/incidentDetails.html

LHS padding removed.
Expands slightly to accommodate invalid inputs
valid input
invalid input

DCS-719: adjusted spacing inside date field. 

---

assets/sass/local.sass
server/views/partials/incidentSearchPanel.html

The css classes that have been removed are not used elsewhere in the app so this change does not affect any other pages
screenshots
**before**
**after**

DCS-727 CSS changes to change width of date fields.

---

integration-tests/integration/createIncident/view-your-report.spec.js
integration-tests/mockApis/elite2api.js
integration-tests/pages/yourReports/yourReportPage.js
integration-tests/plugins/index.js
server/data/elite2ClientBuilder.test.ts
server/data/elite2ClientBuilder.ts

Handled in two ways:
* When searching for details of a location ask prison-api to include inactive locations in the response.
* If prison-api replies 'Not Found' to a location request handle this and carry on.  The locationService already returns empty objects for particular conditions so I've assumed that its clients know how to deal with a Location that isn't.  The only change then is to ensure that elite2ClientBuilder.getLocation handles a 404 response by returning an empty object.

DCS-878 Make retrieval of locations more robust

---

server/routes/creatingReports/incidentDetails.test.ts
server/routes/creatingReports/incidentDetails.ts

Once a field had been stored on the incident details page, if you then cleared out the value and clicked save, it would show the correct validation message but the old field value.
Moved to use the same pattern that we use on other form pages, which is:
If there is any flash then use that otherwise use values from the DB.
Previously it was showing the fields from the db and then overriding with flash entries which doesn't work when data is not present at all in flash

DCS-848 Fixing issue around showing stale data

---

server/data/prisonClient.test.ts
server/data/prisonClient.ts
server/data/statementsClient.test.ts
server/data/statementsClient.ts
server/data/statementsClientTypes.ts
server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/routes/maintainingReports/index.ts
server/services/involvedStaffService.ts
server/services/userService.test.ts
server/services/userService.ts
server/views/pages/coordinator/staff-member-not-removed.html
server/views/pages/coordinator/view-removal-request.html
server/views/pages/reviewer/view-statements.html

User presented with the new page when selecting the View removal request link (if available) from the view-statements page. The new page displays the involved staff member details and their current caseload.
Images of new pages. 
Only the first page needed validation.

DCS-909: first commit - GET journey

---

server/config/types.ts
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/data/statementsClient.test.ts
server/data/statementsClient.ts
server/services/statementService.test.ts
server/services/statementService.ts

We used to set the status but this made it tricky to workout how to determine whether people were requesting to remove a pending statement or submitted one
It turned out we needed to present statements based on their status before requesting removal

DCS-948 Use removal request date as source of truth of removal status

---

server/config.js
server/data/statementsClient.test.ts
server/data/statementsClient.ts
server/data/statementsClientTypes.ts
server/routes/maintainingReports/coordinator.test.ts
server/services/index.ts
server/services/involvedStaffService.test.ts
server/services/involvedStaffService.ts
server/services/notificationService.js
server/services/notificationService.test.js
server/services/reportDetailBuilder.test.ts

There are two ways an involved staff can be removed from an incident report.
First is by coordinator using the 'delete' link in view-report page and the second
is the coordinator using the 'view removal request' link in view-statements and following the process through.
Ultimately they both do the same thing. The action to send an email to the involved staff member starts in the involvedStaffService.removeInvolvedStaff() method. 
It contains new code notificationService.sendInvolvedStaffRemovedFromReport(...) to send the email.
A new template has been created in Govuk Notify.
example of email

DCS-910: email will be sent when involved staff removed

---

server/data/incidentClient.test.ts
server/data/incidentClient.ts

Bug fix.
Identified email reminders being sent even though a removal request had been made by involved staff. 
DB client sql changed so only returns results where there is no removal_requested_date

DCS-947 email reminders sent only if removal has not been requested

---

server/data/statementsClient.test.ts
server/data/statementsClient.ts
server/data/statementsClientTypes.ts
server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/services/involvedStaffService.test.ts
server/services/involvedStaffService.ts

This ticket was about preventing the coordinator landing on the /vew-removal-request page if they had already decided to disallow an involved member's request to be removed from the report. 
The normal flow is /view-statements —> /view-removal-request —> /staff-member-not-removed
The /staff-member-not-removed page contains a hyperlink to return back to /view-statements  but if the coordinator chooses to use the browser back button instead, the browser will try to return to /view-removal-request. We want to prevent this. So in all cases the return from /staff-member-not-removed should be to  /view-statements
There are 2 data items in the DB to indicate a current removal request: the removal_requested_date and the removal_requested_reason. If a coordinator is on the …

DCS-958 coordinator will be redirected to view-statements page

---

server/views/macros.njk
server/views/pages/report-use-of-force.html
server/views/pages/reviewer/view-report.html
server/views/pages/reviewer/view-statements.html
server/views/pages/statement/add-comment-to-statement.html
server/views/pages/statement/write-your-statement.html
server/views/pages/statement/your-statement.html
server/views/pages/your-report.html
server/views/partials/breadcrumbs.njk
server/views/partials/incidentPage.html

Added back link to Digital Prison Services on the page showing Not Completed, Completed, Your statements and Your reports tabs as well (as the report use of force page):
Added 'Digital Prison Services > Use of force incidents' breadcrumb path to lower level incident pages:
Do we need integration tests to check these links (back link and breadcrumbs) work as they should?

DCS-895 added breadcrumbs

---

helm_deploy/use-of-force/templates/_envs.tpl
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.js

The feature toggle was applied to determine the content of emails sent to involved staff. The new content included a link the user could click in order to request they be removed from the UoF report. 
An env var called DISPUTE_INVOLVEMENT_ENABLED had been set to true for all environments that were using the new email templates. Because the templates are now used by dev, pre and prod, i.e all of them,  there is no need to have a feature toggle anymore. So DISPUTE_INVOLVEMENT_ENABLED removed from helm and the associated disputeInvolvementEnabled removed from config.js
Have not deleted old email templates from GovNotify

DCS-986 removed the feature toggle for disputed involvement

---

server/services/involvedStaffService.test.ts
server/services/involvedStaffService.ts

Application error if coordinator attempted to add an involved staff who was already in the report. Error only happened if the username was input in lower or mixed case rather than all uppercase.
Fix was to supply the uppercased username string when checking if user was already in the report.

DCS-1001-bugfix for username

---

server/data/draftReportClient.test.ts
server/data/draftReportClient.ts
server/data/draftReportClientTypes.ts
server/routes/creatingReports/incidentDetails.test.ts
server/services/drafts/draftReportService.test.ts
server/services/drafts/draftReportService.ts

1. moved filtering out in-progress reports from the draft report service to the db client which also now returns the locationId rather than its parent object, to simplify code
2. renamed a test that suggested reports could be saved without an incident date. In fact the code was related
to updating an existing draft report. Reentering a date is not mandatory as it may be the user wants to change other values instead. Test description now reflects this.

DCS-1094: code refactored to move filtering to DB query

---

server/services/prisonerSearchService.test.ts
server/services/prisonerSearchService.ts

When a user searches for a prisoner via caseload on the Search for a prisoner page the list of prisons is now ordered alphabetically.
Previously unsorted:
Now sorted:

DCS-1116 sorted prison list on Search for a prisoner page

---

server/middleware/populateCurrentUser.js

If non prison users log into UoF and try to access the feedback survey link the link is missing hostname and current url path information as this was only set when a current prison user is present. Updated populate current user middleware to set these parameters whether a user is present or not as a short term fix. Maybe in the future UoF should not allow non prison users to access it.

DCS-1135 fix for feedback survey link

---

package-lock.json

fix
```
+-------------+------------------+----------+-------------------+---------------+--------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                TITLE                 |
+-------------+------------------+----------+-------------------+---------------+--------------------------------------+
| json-schema | CVE-2021-3918    | CRITICAL | 0.2.3             | 0.4.0         | nodejs-json-schema: Prototype        |
|             |                  |          |                   |               | pollution vulnerability              |
|             |                  |          |                   |               | -->avd.aquasec.com/nvd/cve-2021-3918 |
+-------------+------------------+----------+-------------------+- …
```

DCS-1341 update package-lock.json

---

integration-tests/pages/sections/reportDetails.js
server/data/prisonClient.test.ts
server/data/prisonClient.ts
server/routes/creatingReports/checkYourAnswers.test.ts
server/routes/creatingReports/checkYourAnswers.ts
server/services/drafts/draftReportService.test.ts
server/services/drafts/draftReportService.ts
server/services/locationService.test.ts
server/services/locationService.ts
server/services/reportDetailBuilder.test.ts
server/services/reportDetailBuilder.ts

Amended the location data format to user description rather than all upper case description. Changed in check your answers and report detail sections

User location displayed as title case

---

assets/sass/local.sass
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.js
server/utils/nunjucksSetup.ts
server/views/pages/report-use-of-force.html
server/views/partials/incidentPage.html

To be deployed to prod 17/7/23
( related to downtime for redis upgrade in prod. See MAP-167 )
FEATURE_FLAG_OUTAGE_BANNER_ENABLED is defaulted to false. Top be set to true directly in  kubernetes deployments either via kubectl or Lens. 
looks like this

MAP-114 add notification banner for downtime

---

package-lock.json
package.json

updated app insights to 2.7.3
both @opentelemetry/instrumentation and import-in-the-middle are child dependencies of app insights

MAP-260 update application insights version

---

server/views/pages/report-use-of-force.html
server/views/partials/incidentPage.html
server/views/partials/layout.html

replace backlinks with breadcrumbs in order to remove the < at beginning of breadcrumb. Applies to 2 pages:

Map 267 uof fix breadcrumb

---

.circleci/config.yml
Dockerfile
cypress.config.ts
package-lock.json
package.json

updated cypress to fix the vulnerability associated with the request library used by cypress.
Found vulnerable advisory paths:
GHSA-p8p7-x288-28g6|cypress>@cypress/request
Failed security audit due to moderate vulnerabilities.
Also added experimentalRunAllSpecs so can run ui specs in single click

MAP-286 - cypress updated to latest

---

server/views/pages/report-use-of-force.html
server/views/partials/incidentPage.html

Required because Nomis will be down
FEATURE_FLAG_OUTAGE_BANNER_ENABLED to be set to true in kube deployment directly

MAP-312 display service outage banner. 

---

docker-compose.yml

Upgrade Redis container image to 7.2 to match the live environment.
Also this makes it compatible with M1 MacBook Pro.

chore: Upgrade Redis container image to 7.2 to match the live environment

---

feature.env
helm_deploy/use-of-force/templates/_envs.tpl
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration-tests/mockApis/auth.js
server/config.js
server/data/authClient.test.ts
server/data/authClient.ts

This has been split out into a new API. It was once part of HMPPS Auth.
https://dsdmoj.atlassian.net/browse/MAP-305

MAP-305: Use HMPPS Manage Users API for user details

---

assets/sass/local.sass

MAP-402 fixed header bar alignment

---

assets/js/add-another-evidence.js
integration-tests/integration/createIncident/form-submit.cy.js
integration-tests/integration/reportPages/enter-use-of-force-details.cy.js
integration-tests/integration/seedData.js
integration-tests/pages/createReport/evidencePage.js
integration-tests/pages/createReport/useOfForceDetailsPage.js
server/config/forms/evidenceForm.js
server/config/forms/evidenceValidation.test.js
server/config/forms/useOfForceDetailsForm.js
server/config/forms/useOfForceDetailsValidation.test.js
server/data/UseOfForceReport.ts
server/routes/creatingReports/createReport.test.ts
server/services/drafts/reportStatusChecker.test.ts
server/services/reportDetailBuilder.test.ts
server/services/reportSummary.test.ts
server/services/reportSummary.ts
server/views/formPages/incident/evidence.html
server/views/formPages/incident/useOfForceDetails.html
server/views/formPages/incidentMacros.njk
server/views/pages/reportDetailMacro.njk

[MAP-581](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-581)
Move the body-camera question out of the 'Evidence' page and put in 'Use of force details' page.
The code in the PR will put the body-worn camera responses for any new reports in the correct place of the DB blob. However old reports will still have the data within Evidence section of blob. The long term goal is to run a DB migration to shift the data and [MAP-642](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-642) has been raised to do that work. 
In the meantime I have implemented logic in the [4th commit ](https://github.com/ministryofjustice/use-of-force/pull/672/commits/ca059c6c62044e940c2f9cda9efc70e256b0ddae) of this PR to get the question …

Map 581 move question on body worn cameras to details screen

---

server/app.ts

Hopefully this will make Google Analytics work properly, as it seems to be getting blocked by the browser due to CSP.
[MAP-793]
[MAP-793]: https://dsdmoj.atlassian.net/browse/MAP-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add more hosts to connect-src directive

---

database_refresh/02-cronjob.yaml
database_refresh/adhoc-db-refresh-job.yaml

Align refresh job PG version with app's PG version to fix DB refresh job fails

MAP-1026 align refresh DB version with apps RDS version

---

package.json

Base node image updated from bullseye to bookworm  and also cypress from 13.1.0 to 13.8.1 (to match typescript template project) in previous commit.  
This has caused docker build to fail with _ERROR [builder 7/8] RUN CYPRESS_INSTALL_BINARY=0 npm ci --no-audit_
Updating cypress-multi-reporters and removing dependency override to see if that resolves error

Fix breaking docker build

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json

docker build failing after dependency updates.
error:
` => ERROR [builder 7/8] RUN CYPRESS_INSTALL_BINARY=0 npm ci --no-audit &  24.1s`
Reverting cypress updates to determine the issue
====
Actual problem was not with the cypress version, rather the bookworm-slim not including python. 
Dockerfile updated to install python

MAP-1044 revert cypress to last good docker image build state

---

helm_deploy/values-prod.yaml

These were missed in the recent change to use groups

MAP-1602 adding missing addresses

---

helm_deploy/use-of-force/values.yaml

When we updated the Helm chart it brought some default liveness and readiness probe config that is incompatible with this project. We need to override the probe config in the same way that the TypeScript template project does.
MAP-1670

MAP-1670: Restore the correct liveness and readiness probes

---

helm_deploy/use-of-force/values.yaml

This project actually uses `/health` not `/ping` for health check.
MAP-1670

MAP-1670: Got the health endpoint wrong in the last commit

---

server/app.ts

to reduce the 'Cannot read properties of undefined (reading 'token')' error occurring in fecomponents

MAP-1670 move getting fecomponents to after authorisationMiddleware

---

server/routes/adhocReportActions/addhocActionController.ts
server/routes/adhocReportActions/adhocActionController.test.ts
server/services/reportService.ts

Use a different DB query to get reports  - a query that does not require the report's submitter as an argument

MAP-1625 get report using db query that doesn't require user

---

helm_deploy/use-of-force/templates/job.yaml

the send-reminders cron jobs are intermittently failing. 
Increasing the 'live' time of the job as it may enable the job to complete before it fails
Note a new job is started every 300 seconds

MAP-1874 increase time for which a job will be live

---

integration-tests/mockApis/locationApi.js
server/data/locationClient.test.ts
server/data/locationClient.ts

[MAP-1883](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-1883)
to format and order location names
[MAP-1883]: https://dsdmoj.atlassian.net/browse/MAP-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1883 apply query params to format and order locations

---

helm_deploy/use-of-force/Chart.yaml

This reverts commit 4d9bc7e916b9da55c3232ad213f62af5c41f0779.

Revert "MAP-1937 update helm chart for data extractor (#740)"

---

server/routes/creatingReports/changePrison.test.ts
server/routes/creatingReports/changePrison.ts
server/routes/creatingReports/incidentDetails.test.ts
server/routes/creatingReports/incidentDetails.ts
server/routes/creatingReports/index.ts

[MAP-1745](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-1745)
This code change fixes the scenario where the /incident-details page will not load if an offender is currently in a transfer or has left prison. This is signified by the offenders agencyId being TRN or OUT. 
In such cases, loading of incident-details fails (and throws a 400 error) because TRN and OUT are not actual prisons and getting their internal locations, which are required by the select drop-down on the page, would return an error.
With the new code, when a user selects /incident-details, a check of the agencyId is done. If it's either TRN or OUT then we redirect to the change prison page. The /change-prison endpoint has been renamed to …

Map 1745 UOF bug users unable to access incident details page

---

helm_deploy/use-of-force/templates/job.yaml

The Email reminder cron job fails intermittently. Not sure of the exact cause but have noticed that jobs sometimes run very close to their 300 second 'active' time. 
This code change: 
Gives Jobs a longer time, 600 seconds, before they are treated as failed, see [activeDeadlineSeconds](https://kubernetes.io/docs/concepts/workloads/controllers/job/)
Cleans up completed job at 100 seconds, see [ttlSecondsAfterFinished](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/Cronjobs.html#kubernetes-cronjobs)
We currently run jobs every 5 mins. Have increased that to 15 mins just so that they don't overlap with any currently running jobs

MAP-1937 give jobs longer time to complete. 

---

helm_deploy/use-of-force/templates/job.yaml

helm file format incorrect in last PR. Move `ttlSecondsAfterFinished` to pod spec section

MAP-1937 move ttlSecondsAfterFinished to correct nest

---

helm_deploy/use-of-force/templates/job.yaml

This reverts the changes in previous to commits because it has not made any changes to the cron job failing. 
Kubernetes is still killing the pod with reason _'Pod was active on the node longer than the specified deadline'_
Will investigate further but in meantime will revert ineffectual changes.

Map 1937 uof cron bug revert

---

.circleci/config.yml
Dockerfile
job/sendReminders.ts
package-lock.json
package.json
server/app.ts
server/data/index.ts
server/data/prisonClient.ts
server/data/redisClient.ts
server/services/reportSummary.ts

As per MAP-1940 epic we have to upgrade connect-redis to 8
As Circle CI pipeline claim about node 20 out of date it was required at the same time to upgrade it
Reference Template Typescript (connect-redis update 8)
https://github.com/ministryofjustice/hmpps-template-typescript/pull/492

MAP-1943 redis8 & node22

---

package.json

Pod logs  point to missing 'start' script. Script added as per template project'

MAP-2229 Changes to dockerfile in previous commit caused a build error

---

migrations/20250501000000_form-db.js

New DB table added to hold edit history for reports already submitted. 
In addition to when and by whom the edit was made, it will record the main question, the main answer (eg Yes/No)and potentially secondary answers (example list of check boxes or camera numbers) plus reason for the edit and any additional comments. Note some question sets and answers can be really long, hence the use of 1000 char limit.

MAP-2388 migration for new history table

---

.github/workflows/security_trivy.yml
package-lock.json
package.json

as its Formidable dependency also updated to safe version. Override no longer needed.

MAP-2435 update Superagent and amend trivy scan cron

---

assets/sass/local.sass
integration-tests/integration/coordinator/add-involved-staff.cy.js
integration-tests/integration/coordinator/remove-involved-staff.cy.js
integration-tests/integration/createIncident/view-your-report.cy.js
integration-tests/integration/reviewer/view-report.cy.js
integration-tests/pages/reviewer/viewReportPage.js
integration-tests/pages/sections/reportDetails.js
integration-tests/pages/yourReports/yourReportPage.js
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/data/incidentClientTypes.ts
server/routes/maintainingReports/reviewer.ts
server/routes/viewingReports/incidents.test.ts
server/routes/viewingReports/incidents.ts
server/services/reportDetailBuilder.test.ts
server/services/reportDetailBuilder.ts
server/services/reportService.test.ts
server/services/reportService.ts
server/services/reviewService.test.ts
server/services/reviewService.ts
server/views/pages/reportDetailMacro.njk
server/views/pages/reportDetailSectionsMacros.njk
server/views/pages/reviewer/view-report.html
server/views/pages/your-report.html

Notes: 
Variable renderReportView  in the views is used to differentiate check-your-answers from view-report and your-report. All three use the same underlying macro but the display of check-your-answers is not to be changed.
Some integration tests have been skipped using 'xit'. This is deliberate and the functionality to remove/add nvolved staff and to delete reports is to be in reintroduced at a later stage and the skipped tests should serve as a reminder of the things to test for.

Map 2319 uof redesign report pages to include tab

---

assets/sass/local.sass
server/routes/maintainingReports/reviewer.test.ts
server/routes/maintainingReports/reviewer.ts
server/views/pages/reportDetailSectionsMacros.njk
server/views/pages/reviewer/view-report.html
server/views/pages/your-report.html

[MAP-2316](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?isEligibleForUserSurvey=true&issueParent=391911&selectedIssue=MAP-2316)
1. display the Edit and delete buttons in /view-report to coordinators only
2. include the prisoner profile in /view-report
3. change link text from history to Edit history
4. tests to check existence of rows related to edited reports
[MAP-2316]: https://dsdmoj.atlassian.net/browse/MAP-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Map 2316 uof incident page tabs and navigation part 1

---

integration-tests/integration/coordinator/remove-statement.cy.js
integration-tests/integration/createIncident/view-your-report.cy.js
integration-tests/integration/reviewer/view-report.cy.js
integration-tests/integration/reviewer/view-statement.cy.js
integration-tests/integration/reviewer/view-statements.cy.js
integration-tests/pages/reviewer/viewReportPage.js
integration-tests/pages/reviewer/viewStatementsPage.js
package-lock.json
server/routes/index.ts
server/routes/maintainingReports/reviewer.test.ts
server/routes/maintainingReports/reviewer.ts
server/routes/viewingIncidents/index.ts
server/routes/viewingIncidents/viewIncidents.test.ts
server/routes/viewingIncidents/viewIncidents.ts
server/routes/viewingReports/incidents.test.ts
server/routes/viewingReports/incidents.ts
server/views/pages/completed-incidents.html
server/views/pages/not-completed-incidents.html
server/views/pages/reportDetailMacro.njk
server/views/pages/reportDetailSectionsMacros.njk
server/views/pages/reviewer/view-report.html
server/views/pages/viewIncident/edit-history.njk
server/views/pages/viewIncident/incident.njk
server/views/pages/viewIncident/navigationTabMacro.njk
server/views/pages/viewIncident/report.njk
server/views/pages/viewIncident/statements.njk
server/views/pages/your-report.html
server/views/pages/your-reports.html

[MAP-2316](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?issueParent=391911%2C286167&selectedIssue=MAP-2316)
[MAP-2316]: https://dsdmoj.atlassian.net/browse/MAP-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Note 1: This code change is to create a new route called /view-incident which leads to a page displaying the report, statements and edit history tabs.
Note 2: The report tab's contents were previously added to the /view-report and /your-report pages in error. Have removed that code code from there. 
Note 3: Have skipped rather then deleted some e2e tests  as they may be useful reference when writing new tests for the entire edit flow.

Map 2316 uof add view incident page and routing

---

server/views/pages/viewIncident/statements.njk

Related to [MAP-2326.](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=625e8c18fd06270069bf7ddd&selectedIssue=MAP-2326)
**Changes made:**
- remove reference to location within the statements tab, involved staff table.

Remove location from statements table

---

assets/sass/local.sass
migrations/20250902000000_form_db.js
server/config/edit/incidentDetailsConfig.ts
server/config/edit/questionSequence.ts
server/config/edit/questionSets.ts
server/data/incidentClient.test.ts
server/data/incidentClient.ts
server/routes/__test/appSetup.ts
server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/routes/viewingIncidents/index.ts
server/routes/viewingIncidents/viewIncidents.test.ts
server/routes/viewingIncidents/viewIncidents.ts
server/services/editIncidentDetailsService.test.ts
server/services/editIncidentDetailsService.ts
server/services/editReports/incidentDetails.test.ts
server/services/editReports/incidentDetails.ts
server/services/editReports/types/reportEditServiceTypes.ts
server/services/index.ts
server/services/reportEditService.test.ts
server/services/reportEditService.ts
server/services/reportService.test.ts
server/services/reportService.ts
server/utils/getIncidentDate.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/viewIncident/edit-history.njk

This PR is to enable edits to the incident-details page
Have added a DB migration so that changes will now be stored in a jsonb blob rather than individual columns (old_value_primary, old_value_secondary etc)
Use of the bob follows the pattern in the actual original report

Map 2636 uof edit incident details persist edits to edits table

---

assets/sass/components/_pagination.scss
integration-tests/integration/statements/view-your-statements.cy.js
server/views/pages/completed-incidents.html
server/views/pages/not-completed-incidents.html
server/views/pages/your-reports.html
server/views/pages/your-statements.html

Small update to display only the 'Showing x to x of x results' part of the pagination component when there is only 1 page of results. 
- Added new style to hide the additional unneeded part of the pagination component in this case
- Updated the appropriate views
- Updated integration test

MAP-2646 - Update pagination for single page of results

---

server/routes/maintainingReports/coordinator.test.ts
server/routes/maintainingReports/coordinator.ts
server/services/editReports/reasonsForUseOfForce.test.ts
server/services/editReports/reasonsForUseOfForce.ts

Some old reports don't have reasonsForUseOfForce in their dataset. 
This code is to prevent an application crash for those reports by checking whether the data exists before trying to access the reasons value
see `report.form.reasonsForUseOfForce?.reasons || []` and `report.form.reasonsForUseOfForce?.primaryReason || ''`

MAP-2798 handle report edits where reasonsForUseOfForce does not exist
